part of 'tv_screensaver_section.dart';

extension _TvScreensaverSectionVisualBuild on _TvScreensaverSectionState {
  List<Widget> _buildVisualSection({
    required SettingsProvider settings,
    required ColorScheme colorScheme,
    required TextTheme textTheme,
    required bool isFruit,
  }) {
    return [
      _SectionHeader(title: 'Visual', colorScheme: colorScheme),
      const SizedBox(height: 8),
      Text(
        'Color Palette',
        style: textTheme.bodySmall?.copyWith(
          color: colorScheme.onSurfaceVariant,
        ),
      ),
      const SizedBox(height: 8),
      _PaletteSegmentedButton(
        selected: settings.oilPalette,
        onSelect: (key) => settings.setOilPalette(key),
        colorScheme: colorScheme,
      ),
      const SizedBox(height: 24),
      _ToggleRow(
        label: 'Flat Color Mode',
        subtitle: 'Use a single static palette color instead of animation',
        value: settings.oilFlatColor,
        onChanged: (_) => settings.toggleOilFlatColor(),
        colorScheme: colorScheme,
        textTheme: textTheme,
      ),
      const SizedBox(height: 16),
      _ToggleRow(
        label: 'Auto Palette Cycle',
        subtitle: 'Automatically rotate through palettes over time',
        value: settings.oilPaletteCycle,
        onChanged: (_) => settings.toggleOilPaletteCycle(),
        colorScheme: colorScheme,
        textTheme: textTheme,
      ),
      const SizedBox(height: 24),
      TvStepperRow(
        label: 'Logo Scale',
        value: settings.oilLogoScale,
        min: 0.1,
        max: 1.0,
        step: 0.05,
        leftLabel: 'Small',
        rightLabel: 'Full',
        valueFormatter: (v) => '${(v * 100).round()}%',
        onChanged: (v) => settings.setOilLogoScale(v),
      ),
      const SizedBox(height: 8),
      if (settings.oilEnableAudioReactivity)
        _ReactiveHint(
          message:
              'Audio reactive: beat pulses are applied on top of this base '
              'size.',
          colorScheme: colorScheme,
          textTheme: textTheme,
          isFruit: isFruit,
        ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Trail Intensity',
        value: settings.oilLogoTrailIntensity,
        min: 0.0,
        max: 1.0,
        step: 0.05,
        leftLabel: 'Off',
        rightLabel: 'Strong',
        valueFormatter: (v) => '${(v * 100).round()}%',
        onChanged: (v) => settings.setOilLogoTrailIntensity(v),
      ),
      const SizedBox(height: 16),
      _ToggleRow(
        label: 'Dynamic Trails',
        subtitle: 'Scale trail quality based on movement speed',
        value: settings.oilLogoTrailDynamic,
        onChanged: (_) => settings.toggleOilLogoTrailDynamic(),
        colorScheme: colorScheme,
        textTheme: textTheme,
      ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Trail Slices',
        value: settings.oilLogoTrailSlices.toDouble(),
        min: 2,
        max: 16,
        step: 1,
        leftLabel: 'Slight',
        rightLabel: 'Liquid',
        valueFormatter: (v) => v.round().toString(),
        onChanged: (v) => settings.setOilLogoTrailSlices(v.round()),
      ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Trail Spread',
        value: settings.oilLogoTrailLength,
        min: 0.0,
        max: 2.0,
        step: 0.05,
        leftLabel: 'Tight',
        rightLabel: 'Long',
        valueFormatter: (v) => '${(v * 100).round()}%',
        onChanged: (v) => settings.setOilLogoTrailLength(v),
      ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Trail Initial Scale',
        value: settings.oilLogoTrailInitialScale,
        min: 0.5,
        max: 2.0,
        step: 0.05,
        leftLabel: '50%',
        rightLabel: '200%',
        valueFormatter: (v) =>
            v == 1.0 ? '100% (Native)' : '${(v * 100).round()}%',
        onChanged: (v) => settings.setOilLogoTrailInitialScale(v),
      ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Trail Decay Scale',
        value: settings.oilLogoTrailScale,
        min: 0.0,
        max: 0.5,
        step: 0.05,
        leftLabel: '1:1',
        rightLabel: 'Taper',
        valueFormatter: (v) => v == 0.0 ? 'None' : '-${(v * 100).round()}%',
        onChanged: (v) => settings.setOilLogoTrailScale(v),
      ),
      TvStepperRow(
        label: 'Logo Blur',
        value: settings.oilBlurAmount,
        min: 0.0,
        max: 1.0,
        step: 0.05,
        leftLabel: 'Sharp',
        rightLabel: 'Soft',
        valueFormatter: (v) => '${(v * 100).round()}%',
        onChanged: (v) => settings.setOilBlurAmount(v),
      ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Motion Smoothing',
        value: settings.oilTranslationSmoothing,
        min: 0.0,
        max: 1.0,
        step: 0.05,
        leftLabel: 'Crisp',
        rightLabel: 'Smooth',
        valueFormatter: (v) => '${(v * 100).round()}%',
        onChanged: (v) => settings.setOilTranslationSmoothing(v),
      ),
      const SizedBox(height: 24),
      TvStepperRow(
        label: 'Flow Speed',
        value: settings.oilFlowSpeed,
        min: 0.01,
        max: 1.0,
        step: 0.01,
        leftLabel: 'Slow',
        rightLabel: 'Fast',
        valueFormatter: (v) => v.toStringAsFixed(2),
        onChanged: (v) => settings.setOilFlowSpeed(v),
      ),
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Pulse Intensity',
        value: settings.oilPulseIntensity,
        min: 0.0,
        max: 3.0,
        step: 0.1,
        leftLabel: 'Subtle',
        rightLabel: 'Strong',
        onChanged: (v) => settings.setOilPulseIntensity(v),
      ),
      if (settings.oilEnableAudioReactivity) ...[
        const SizedBox(height: 8),
        _ReactiveHint(
          message:
              'Audio reactive: higher values amplify bass-driven logo '
              'expansion.',
          colorScheme: colorScheme,
          textTheme: textTheme,
          isFruit: isFruit,
        ),
      ],
      const SizedBox(height: 16),
      TvStepperRow(
        label: 'Heat Drift',
        value: settings.oilHeatDrift,
        min: 0.0,
        max: 3.0,
        step: 0.1,
        leftLabel: 'Still',
        rightLabel: 'Wavy',
        onChanged: (v) => settings.setOilHeatDrift(v),
      ),
      const SizedBox(height: 24),
      _ToggleRow(
        label: 'Sine Wave Drive',
        subtitle: 'Modulate logo scale with a periodic wave',
        value: settings.oilScaleSineEnabled,
        onChanged: (_) => settings.toggleOilScaleSineEnabled(),
        colorScheme: colorScheme,
        textTheme: textTheme,
      ),
      if (settings.oilScaleSineEnabled) ...[
        const SizedBox(height: 16),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Column(
            children: [
              TvStepperRow(
                label: 'Sine Frequency',
                value: settings.oilScaleSineFreq,
                min: 0.01,
                max: 10.0,
                step: 0.05,
                onChanged: settings.setOilScaleSineFreq,
                valueFormatter: (v) => '${v.toStringAsFixed(2)} Hz',
              ),
              const SizedBox(height: 12),
              TvStepperRow(
                label: 'Sine Amplitude',
                value: settings.oilScaleSineAmp,
                min: 0.0,
                max: 1.0,
                step: 0.05,
                onChanged: settings.setOilScaleSineAmp,
                valueFormatter: (v) => '${(v * 100).round()}%',
              ),
            ],
          ),
        ),
      ],
      const SizedBox(height: 24),
    ];
  }
}
