// Mocks generated by Mockito 5.4.4 from annotations
// in shakedown/test/screensaver_exit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:just_audio/just_audio.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:shakedown/models/show.dart' as _i10;
import 'package:shakedown/models/source.dart' as _i11;
import 'package:shakedown/providers/audio_provider.dart' as _i8;
import 'package:shakedown/providers/settings_provider.dart' as _i3;
import 'package:shakedown/providers/show_list_provider.dart' as _i12;
import 'package:shakedown/providers/theme_provider.dart' as _i5;
import 'package:shakedown/services/audio_cache_service.dart' as _i13;
import 'package:shakedown/services/gapless_player/gapless_player.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGaplessPlayer_0 extends _i1.SmartFake implements _i2.GaplessPlayer {
  _FakeGaplessPlayer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i3.SettingsProvider {
  @override
  bool get isTv => (super.noSuchMethod(
        Invocation.getter(#isTv),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showExpandIcon => (super.noSuchMethod(
        Invocation.getter(#showExpandIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set showExpandIcon(bool? _showExpandIcon) => super.noSuchMethod(
        Invocation.setter(
          #showExpandIcon,
          _showExpandIcon,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get appFont => (super.noSuchMethod(
        Invocation.getter(#appFont),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#appFont),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#appFont),
        ),
      ) as String);

  @override
  bool get showSplashScreen => (super.noSuchMethod(
        Invocation.getter(#showSplashScreen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isFirstRun => (super.noSuchMethod(
        Invocation.getter(#isFirstRun),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showOnboarding => (super.noSuchMethod(
        Invocation.getter(#showOnboarding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showTrackNumbers => (super.noSuchMethod(
        Invocation.getter(#showTrackNumbers),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideTrackDuration => (super.noSuchMethod(
        Invocation.getter(#hideTrackDuration),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playOnTap => (super.noSuchMethod(
        Invocation.getter(#playOnTap),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showSingleShnid => (super.noSuchMethod(
        Invocation.getter(#showSingleShnid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideTrackCountInSourceList => (super.noSuchMethod(
        Invocation.getter(#hideTrackCountInSourceList),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playRandomOnCompletion => (super.noSuchMethod(
        Invocation.getter(#playRandomOnCompletion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get nonRandom => (super.noSuchMethod(
        Invocation.getter(#nonRandom),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playRandomOnStartup => (super.noSuchMethod(
        Invocation.getter(#playRandomOnStartup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get dateFirstInShowCard => (super.noSuchMethod(
        Invocation.getter(#dateFirstInShowCard),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useDynamicColor => (super.noSuchMethod(
        Invocation.getter(#useDynamicColor),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useTrueBlack => (super.noSuchMethod(
        Invocation.getter(#useTrueBlack),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useSliverAppBar => (super.noSuchMethod(
        Invocation.getter(#useSliverAppBar),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useSharedAxisTransition => (super.noSuchMethod(
        Invocation.getter(#useSharedAxisTransition),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get uiScale => (super.noSuchMethod(
        Invocation.getter(#uiScale),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get glowMode => (super.noSuchMethod(
        Invocation.getter(#glowMode),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get highlightPlayingWithRgb => (super.noSuchMethod(
        Invocation.getter(#highlightPlayingWithRgb),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showPlaybackMessages => (super.noSuchMethod(
        Invocation.getter(#showPlaybackMessages),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDevAudioHud => (super.noSuchMethod(
        Invocation.getter(#showDevAudioHud),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get devAudioHudSnapshot => (super.noSuchMethod(
        Invocation.getter(#devAudioHudSnapshot),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#devAudioHudSnapshot),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#devAudioHudSnapshot),
        ),
      ) as String);

  @override
  bool get sortOldestFirst => (super.noSuchMethod(
        Invocation.getter(#sortOldestFirst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useStrictSrcCategorization => (super.noSuchMethod(
        Invocation.getter(#useStrictSrcCategorization),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get offlineBuffering => (super.noSuchMethod(
        Invocation.getter(#offlineBuffering),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableBufferAgent => (super.noSuchMethod(
        Invocation.getter(#enableBufferAgent),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get preventSleep => (super.noSuchMethod(
        Invocation.getter(#preventSleep),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get highlightCurrentShowCard => (super.noSuchMethod(
        Invocation.getter(#highlightCurrentShowCard),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useMaterial3 => (super.noSuchMethod(
        Invocation.getter(#useMaterial3),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#showDayOfWeek),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get abbreviateDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#abbreviateDayOfWeek),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get abbreviateMonth => (super.noSuchMethod(
        Invocation.getter(#abbreviateMonth),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get simpleRandomIcon => (super.noSuchMethod(
        Invocation.getter(#simpleRandomIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get fruitDenseList => (super.noSuchMethod(
        Invocation.getter(#fruitDenseList),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get marqueeEnabled => (super.noSuchMethod(
        Invocation.getter(#marqueeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableSwipeToBlock => (super.noSuchMethod(
        Invocation.getter(#enableSwipeToBlock),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get omitHttpPathInCopy => (super.noSuchMethod(
        Invocation.getter(#omitHttpPathInCopy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useNeumorphism => (super.noSuchMethod(
        Invocation.getter(#useNeumorphism),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get fruitEnableLiquidGlass => (super.noSuchMethod(
        Invocation.getter(#fruitEnableLiquidGlass),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get fruitStickyNowPlaying => (super.noSuchMethod(
        Invocation.getter(#fruitStickyNowPlaying),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableHaptics => (super.noSuchMethod(
        Invocation.getter(#enableHaptics),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.NeumorphicStyle get neumorphicStyle => (super.noSuchMethod(
        Invocation.getter(#neumorphicStyle),
        returnValue: _i5.NeumorphicStyle.convex,
        returnValueForMissingStub: _i5.NeumorphicStyle.convex,
      ) as _i5.NeumorphicStyle);

  @override
  bool get performanceMode => (super.noSuchMethod(
        Invocation.getter(#performanceMode),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get forceTv => (super.noSuchMethod(
        Invocation.getter(#forceTv),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.AudioEngineMode get audioEngineMode => (super.noSuchMethod(
        Invocation.getter(#audioEngineMode),
        returnValue: _i2.AudioEngineMode.auto,
        returnValueForMissingStub: _i2.AudioEngineMode.auto,
      ) as _i2.AudioEngineMode);

  @override
  bool get webGaplessEngine => (super.noSuchMethod(
        Invocation.getter(#webGaplessEngine),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get webPrefetchSeconds => (super.noSuchMethod(
        Invocation.getter(#webPrefetchSeconds),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get trackTransitionMode => (super.noSuchMethod(
        Invocation.getter(#trackTransitionMode),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#trackTransitionMode),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#trackTransitionMode),
        ),
      ) as String);

  @override
  double get crossfadeDurationSeconds => (super.noSuchMethod(
        Invocation.getter(#crossfadeDurationSeconds),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i2.HybridHandoffMode get hybridHandoffMode => (super.noSuchMethod(
        Invocation.getter(#hybridHandoffMode),
        returnValue: _i2.HybridHandoffMode.buffered,
        returnValueForMissingStub: _i2.HybridHandoffMode.buffered,
      ) as _i2.HybridHandoffMode);

  @override
  _i2.HybridBackgroundMode get hybridBackgroundMode => (super.noSuchMethod(
        Invocation.getter(#hybridBackgroundMode),
        returnValue: _i2.HybridBackgroundMode.html5,
        returnValueForMissingStub: _i2.HybridBackgroundMode.html5,
      ) as _i2.HybridBackgroundMode);

  @override
  bool get allowHiddenWebAudio => (super.noSuchMethod(
        Invocation.getter(#allowHiddenWebAudio),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get handoffCrossfadeMs => (super.noSuchMethod(
        Invocation.getter(#handoffCrossfadeMs),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get hybridForceHtml5Start => (super.noSuchMethod(
        Invocation.getter(#hybridForceHtml5Start),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.HiddenSessionPreset get hiddenSessionPreset => (super.noSuchMethod(
        Invocation.getter(#hiddenSessionPreset),
        returnValue: _i2.HiddenSessionPreset.stability,
        returnValueForMissingStub: _i2.HiddenSessionPreset.stability,
      ) as _i2.HiddenSessionPreset);

  @override
  _i3.WebEngineProfile get webEngineProfile => (super.noSuchMethod(
        Invocation.getter(#webEngineProfile),
        returnValue: _i3.WebEngineProfile.modern,
        returnValueForMissingStub: _i3.WebEngineProfile.modern,
      ) as _i3.WebEngineProfile);

  @override
  bool get useOilScreensaver => (super.noSuchMethod(
        Invocation.getter(#useOilScreensaver),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get oilScreensaverMode => (super.noSuchMethod(
        Invocation.getter(#oilScreensaverMode),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilScreensaverMode),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilScreensaverMode),
        ),
      ) as String);

  @override
  int get oilScreensaverInactivityMinutes => (super.noSuchMethod(
        Invocation.getter(#oilScreensaverInactivityMinutes),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  double get oilFlowSpeed => (super.noSuchMethod(
        Invocation.getter(#oilFlowSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilPulseIntensity => (super.noSuchMethod(
        Invocation.getter(#oilPulseIntensity),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get oilPalette => (super.noSuchMethod(
        Invocation.getter(#oilPalette),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilPalette),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilPalette),
        ),
      ) as String);

  @override
  double get oilFilmGrain => (super.noSuchMethod(
        Invocation.getter(#oilFilmGrain),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilHeatDrift => (super.noSuchMethod(
        Invocation.getter(#oilHeatDrift),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilEnableAudioReactivity => (super.noSuchMethod(
        Invocation.getter(#oilEnableAudioReactivity),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get oilPerformanceLevel => (super.noSuchMethod(
        Invocation.getter(#oilPerformanceLevel),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get oilPaletteCycle => (super.noSuchMethod(
        Invocation.getter(#oilPaletteCycle),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilPaletteTransitionSpeed => (super.noSuchMethod(
        Invocation.getter(#oilPaletteTransitionSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get oilBannerDisplayMode => (super.noSuchMethod(
        Invocation.getter(#oilBannerDisplayMode),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilBannerDisplayMode),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilBannerDisplayMode),
        ),
      ) as String);

  @override
  String get oilBannerFont => (super.noSuchMethod(
        Invocation.getter(#oilBannerFont),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilBannerFont),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilBannerFont),
        ),
      ) as String);

  @override
  double get oilFlatTextProximity => (super.noSuchMethod(
        Invocation.getter(#oilFlatTextProximity),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get oilFlatTextPlacement => (super.noSuchMethod(
        Invocation.getter(#oilFlatTextPlacement),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilFlatTextPlacement),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilFlatTextPlacement),
        ),
      ) as String);

  @override
  double get oilBannerResolution => (super.noSuchMethod(
        Invocation.getter(#oilBannerResolution),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilBannerPixelSnap => (super.noSuchMethod(
        Invocation.getter(#oilBannerPixelSnap),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilBannerLetterSpacing => (super.noSuchMethod(
        Invocation.getter(#oilBannerLetterSpacing),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilBannerWordSpacing => (super.noSuchMethod(
        Invocation.getter(#oilBannerWordSpacing),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilTrackLetterSpacing => (super.noSuchMethod(
        Invocation.getter(#oilTrackLetterSpacing),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilTrackWordSpacing => (super.noSuchMethod(
        Invocation.getter(#oilTrackWordSpacing),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilFlatLineSpacing => (super.noSuchMethod(
        Invocation.getter(#oilFlatLineSpacing),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilLogoTrailIntensity => (super.noSuchMethod(
        Invocation.getter(#oilLogoTrailIntensity),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  int get oilLogoTrailSlices => (super.noSuchMethod(
        Invocation.getter(#oilLogoTrailSlices),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get oilLogoTrailDynamic => (super.noSuchMethod(
        Invocation.getter(#oilLogoTrailDynamic),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilLogoTrailLength => (super.noSuchMethod(
        Invocation.getter(#oilLogoTrailLength),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilLogoTrailScale => (super.noSuchMethod(
        Invocation.getter(#oilLogoTrailScale),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilLogoTrailInitialScale => (super.noSuchMethod(
        Invocation.getter(#oilLogoTrailInitialScale),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilAudioPeakDecay => (super.noSuchMethod(
        Invocation.getter(#oilAudioPeakDecay),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilAudioBassBoost => (super.noSuchMethod(
        Invocation.getter(#oilAudioBassBoost),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilAudioReactivityStrength => (super.noSuchMethod(
        Invocation.getter(#oilAudioReactivityStrength),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get oilAudioGraphMode => (super.noSuchMethod(
        Invocation.getter(#oilAudioGraphMode),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilAudioGraphMode),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#oilAudioGraphMode),
        ),
      ) as String);

  @override
  double get oilEkgRadius => (super.noSuchMethod(
        Invocation.getter(#oilEkgRadius),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  int get oilEkgReplication => (super.noSuchMethod(
        Invocation.getter(#oilEkgReplication),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  double get oilBeatSensitivity => (super.noSuchMethod(
        Invocation.getter(#oilBeatSensitivity),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilBeatImpact => (super.noSuchMethod(
        Invocation.getter(#oilBeatImpact),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilShowInfoBanner => (super.noSuchMethod(
        Invocation.getter(#oilShowInfoBanner),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilLogoScale => (super.noSuchMethod(
        Invocation.getter(#oilLogoScale),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilTranslationSmoothing => (super.noSuchMethod(
        Invocation.getter(#oilTranslationSmoothing),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilBlurAmount => (super.noSuchMethod(
        Invocation.getter(#oilBlurAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilFlatColor => (super.noSuchMethod(
        Invocation.getter(#oilFlatColor),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get oilBannerGlow => (super.noSuchMethod(
        Invocation.getter(#oilBannerGlow),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilBannerFlicker => (super.noSuchMethod(
        Invocation.getter(#oilBannerFlicker),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilBannerGlowBlur => (super.noSuchMethod(
        Invocation.getter(#oilBannerGlowBlur),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilLogoAntiAlias => (super.noSuchMethod(
        Invocation.getter(#oilLogoAntiAlias),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilInnerRingScale => (super.noSuchMethod(
        Invocation.getter(#oilInnerRingScale),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilInnerToMiddleGap => (super.noSuchMethod(
        Invocation.getter(#oilInnerToMiddleGap),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilMiddleToOuterGap => (super.noSuchMethod(
        Invocation.getter(#oilMiddleToOuterGap),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilOrbitDrift => (super.noSuchMethod(
        Invocation.getter(#oilOrbitDrift),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilInnerRingFontScale => (super.noSuchMethod(
        Invocation.getter(#oilInnerRingFontScale),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilInnerRingSpacingMultiplier => (super.noSuchMethod(
        Invocation.getter(#oilInnerRingSpacingMultiplier),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilScreensaver4kSupport => (super.noSuchMethod(
        Invocation.getter(#oilScreensaver4kSupport),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get oilTvPremiumHighlight => (super.noSuchMethod(
        Invocation.getter(#oilTvPremiumHighlight),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get oilScaleSource => (super.noSuchMethod(
        Invocation.getter(#oilScaleSource),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  double get oilScaleMultiplier => (super.noSuchMethod(
        Invocation.getter(#oilScaleMultiplier),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  int get oilColorSource => (super.noSuchMethod(
        Invocation.getter(#oilColorSource),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  double get oilColorMultiplier => (super.noSuchMethod(
        Invocation.getter(#oilColorMultiplier),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilWoodstockEveryHour => (super.noSuchMethod(
        Invocation.getter(#oilWoodstockEveryHour),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomOnlyUnplayed => (super.noSuchMethod(
        Invocation.getter(#randomOnlyUnplayed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomOnlyHighRated => (super.noSuchMethod(
        Invocation.getter(#randomOnlyHighRated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomExcludePlayed => (super.noSuchMethod(
        Invocation.getter(#randomExcludePlayed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showGlobalAlbumArt => (super.noSuchMethod(
        Invocation.getter(#showGlobalAlbumArt),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasShownAdvancedCacheSuggestion => (super.noSuchMethod(
        Invocation.getter(#hasShownAdvancedCacheSuggestion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDebugLayout => (super.noSuchMethod(
        Invocation.getter(#showDebugLayout),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableShakedownTween => (super.noSuchMethod(
        Invocation.getter(#enableShakedownTween),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.DevHudMode get devHudMode => (super.noSuchMethod(
        Invocation.getter(#devHudMode),
        returnValue: _i3.DevHudMode.full,
        returnValueForMissingStub: _i3.DevHudMode.full,
      ) as _i3.DevHudMode);

  @override
  double get rgbAnimationSpeed => (super.noSuchMethod(
        Invocation.getter(#rgbAnimationSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get filterHighestShnid => (super.noSuchMethod(
        Invocation.getter(#filterHighestShnid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, bool> get sourceCategoryFilters => (super.noSuchMethod(
        Invocation.getter(#sourceCategoryFilters),
        returnValue: <String, bool>{},
        returnValueForMissingStub: <String, bool>{},
      ) as Map<String, bool>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setAppFont(String? font) => super.noSuchMethod(
        Invocation.method(
          #setAppFont,
          [font],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> completeOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleShowSplashScreen() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSplashScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseNeumorphism() => super.noSuchMethod(
        Invocation.method(
          #toggleUseNeumorphism,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFruitEnableLiquidGlass() => super.noSuchMethod(
        Invocation.method(
          #toggleFruitEnableLiquidGlass,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFruitEnableLiquidGlass(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setFruitEnableLiquidGlass,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFruitStickyNowPlaying() => super.noSuchMethod(
        Invocation.method(
          #toggleFruitStickyNowPlaying,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAudioEngineMode(_i2.AudioEngineMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setAudioEngineMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTrackTransitionMode(String? mode) => super.noSuchMethod(
        Invocation.method(
          #setTrackTransitionMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCrossfadeDurationSeconds(double? seconds) => super.noSuchMethod(
        Invocation.method(
          #setCrossfadeDurationSeconds,
          [seconds],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHybridHandoffMode(_i2.HybridHandoffMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setHybridHandoffMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAllowHiddenWebAudio(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAllowHiddenWebAudio,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHandoffCrossfadeMs(int? ms) => super.noSuchMethod(
        Invocation.method(
          #setHandoffCrossfadeMs,
          [ms],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHybridForceHtml5Start(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setHybridForceHtml5Start,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHybridBackgroundMode(_i2.HybridBackgroundMode? mode) =>
      super.noSuchMethod(
        Invocation.method(
          #setHybridBackgroundMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHiddenSessionPreset(_i2.HiddenSessionPreset? preset) =>
      super.noSuchMethod(
        Invocation.method(
          #setHiddenSessionPreset,
          [preset],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWebEngineProfile(_i3.WebEngineProfile? profile) => super.noSuchMethod(
        Invocation.method(
          #setWebEngineProfile,
          [profile],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markAdvancedCacheSuggestionShown() => super.noSuchMethod(
        Invocation.method(
          #markAdvancedCacheSuggestionShown,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDebugLayout() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDebugLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableShakedownTween() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableShakedownTween,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetFruitFirstTimeSettings() => super.noSuchMethod(
        Invocation.method(
          #resetFruitFirstTimeSettings,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowTrackNumbers() => super.noSuchMethod(
        Invocation.method(
          #toggleShowTrackNumbers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHideTrackDuration() => super.noSuchMethod(
        Invocation.method(
          #toggleHideTrackDuration,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayOnTap() => super.noSuchMethod(
        Invocation.method(
          #togglePlayOnTap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowSingleShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSingleShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnCompletion() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnCompletion,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleNonRandom() => super.noSuchMethod(
        Invocation.method(
          #toggleNonRandom,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnStartup() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnStartup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleDateFirstInShowCard() => super.noSuchMethod(
        Invocation.method(
          #toggleDateFirstInShowCard,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseDynamicColor() => super.noSuchMethod(
        Invocation.method(
          #toggleUseDynamicColor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseTrueBlack() => super.noSuchMethod(
        Invocation.method(
          #toggleUseTrueBlack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDayOfWeek() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDayOfWeek,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAbbreviateDayOfWeek() => super.noSuchMethod(
        Invocation.method(
          #toggleAbbreviateDayOfWeek,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAbbreviateMonth() => super.noSuchMethod(
        Invocation.method(
          #toggleAbbreviateMonth,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSimpleRandomIcon() => super.noSuchMethod(
        Invocation.method(
          #toggleSimpleRandomIcon,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUiScale() => super.noSuchMethod(
        Invocation.method(
          #toggleUiScale,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGlowMode(int? mode) => super.noSuchMethod(
        Invocation.method(
          #setGlowMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHighlightPlayingWithRgb() => super.noSuchMethod(
        Invocation.method(
          #toggleHighlightPlayingWithRgb,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHighlightPlayingWithRgb(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setHighlightPlayingWithRgb,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowPlaybackMessages() => super.noSuchMethod(
        Invocation.method(
          #toggleShowPlaybackMessages,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDevAudioHud() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDevAudioHud,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDevHudMode(_i3.DevHudMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setDevHudMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cycleDevHudMode() => super.noSuchMethod(
        Invocation.method(
          #cycleDevHudMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> saveDevAudioHudSnapshot(String? snapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDevAudioHudSnapshot,
          [snapshot],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleSortOldestFirst() => super.noSuchMethod(
        Invocation.method(
          #toggleSortOldestFirst,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseStrictSrcCategorization() => super.noSuchMethod(
        Invocation.method(
          #toggleUseStrictSrcCategorization,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOfflineBuffering() => super.noSuchMethod(
        Invocation.method(
          #toggleOfflineBuffering,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableBufferAgent() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableBufferAgent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePreventSleep() => super.noSuchMethod(
        Invocation.method(
          #togglePreventSleep,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableSwipeToBlock() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableSwipeToBlock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOmitHttpPathInCopy() => super.noSuchMethod(
        Invocation.method(
          #toggleOmitHttpPathInCopy,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUseNeumorphism(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setUseNeumorphism,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePerformanceMode() => super.noSuchMethod(
        Invocation.method(
          #togglePerformanceMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleForceTv() => super.noSuchMethod(
        Invocation.method(
          #toggleForceTv,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setForceTv(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setForceTv,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableHaptics() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableHaptics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFruitDenseList() => super.noSuchMethod(
        Invocation.method(
          #toggleFruitDenseList,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOilTvPremiumHighlight() => super.noSuchMethod(
        Invocation.method(
          #toggleOilTvPremiumHighlight,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setNeumorphicStyle(
    _i5.NeumorphicStyle? value, {
    bool? notify,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setNeumorphicStyle,
          [value],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleWebGaplessEngine() => super.noSuchMethod(
        Invocation.method(
          #toggleWebGaplessEngine,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setWebPrefetchSeconds(int? seconds) => (super.noSuchMethod(
        Invocation.method(
          #setWebPrefetchSeconds,
          [seconds],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setRgbAnimationSpeed(double? speed) => super.noSuchMethod(
        Invocation.method(
          #setRgbAnimationSpeed,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setSeedColor(_i7.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #setSeedColor,
          [color],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleRandomOnlyUnplayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyUnplayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomOnlyHighRated() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyHighRated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomExcludePlayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomExcludePlayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseOilScreensaver() => super.noSuchMethod(
        Invocation.method(
          #toggleUseOilScreensaver,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOilScreensaverMode(String? mode) => super.noSuchMethod(
        Invocation.method(
          #setOilScreensaverMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOilScreensaverInactivityMinutes(int? minutes) => super.noSuchMethod(
        Invocation.method(
          #setOilScreensaverInactivityMinutes,
          [minutes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilFlowSpeed(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilFlowSpeed,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilPulseIntensity(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilPulseIntensity,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilPalette(String? palette) => (super.noSuchMethod(
        Invocation.method(
          #setOilPalette,
          [palette],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilFilmGrain(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilFilmGrain,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilHeatDrift(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilHeatDrift,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleOilEnableAudioReactivity() => (super.noSuchMethod(
        Invocation.method(
          #toggleOilEnableAudioReactivity,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilPerformanceLevel(int? level) => (super.noSuchMethod(
        Invocation.method(
          #setOilPerformanceLevel,
          [level],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleOilLogoAntiAlias() => (super.noSuchMethod(
        Invocation.method(
          #toggleOilLogoAntiAlias,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleOilPaletteCycle() => (super.noSuchMethod(
        Invocation.method(
          #toggleOilPaletteCycle,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setOilPaletteTransitionSpeed(double? seconds) => super.noSuchMethod(
        Invocation.method(
          #setOilPaletteTransitionSpeed,
          [seconds],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilBannerDisplayMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setOilBannerDisplayMode,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBannerFont(String? font) => (super.noSuchMethod(
        Invocation.method(
          #setOilBannerFont,
          [font],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilFlatTextProximity(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilFlatTextProximity,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilFlatTextPlacement(String? placement) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilFlatTextPlacement,
          [placement],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBannerLetterSpacing(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilBannerLetterSpacing,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBannerWordSpacing(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilBannerWordSpacing,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilFlatLineSpacing(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilFlatLineSpacing,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilLogoTrailIntensity(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilLogoTrailIntensity,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilLogoTrailSlices(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilLogoTrailSlices,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleOilLogoTrailDynamic() => super.noSuchMethod(
        Invocation.method(
          #toggleOilLogoTrailDynamic,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilLogoTrailLength(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilLogoTrailLength,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilLogoTrailScale(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilLogoTrailScale,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilLogoTrailInitialScale(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilLogoTrailInitialScale,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilAudioPeakDecay(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilAudioPeakDecay,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilAudioBassBoost(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilAudioBassBoost,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilAudioReactivityStrength(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilAudioReactivityStrength,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setOilAudioGraphMode(String? mode) => super.noSuchMethod(
        Invocation.method(
          #setOilAudioGraphMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilBeatSensitivity(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilBeatSensitivity,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBeatImpact(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilBeatImpact,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleOilShowInfoBanner() => super.noSuchMethod(
        Invocation.method(
          #toggleOilShowInfoBanner,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilLogoScale(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilLogoScale,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilTranslationSmoothing(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilTranslationSmoothing,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBlurAmount(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilBlurAmount,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleOilFlatColor() => super.noSuchMethod(
        Invocation.method(
          #toggleOilFlatColor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOilBannerGlow() => super.noSuchMethod(
        Invocation.method(
          #toggleOilBannerGlow,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilBannerFlicker(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilBannerFlicker,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBannerGlowBlur(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilBannerGlowBlur,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilBannerResolution(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilBannerResolution,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleOilBannerPixelSnap() => (super.noSuchMethod(
        Invocation.method(
          #toggleOilBannerPixelSnap,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilInnerRingScale(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilInnerRingScale,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilInnerToMiddleGap(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilInnerToMiddleGap,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilMiddleToOuterGap(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilMiddleToOuterGap,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilOrbitDrift(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilOrbitDrift,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilInnerRingFontScale(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilInnerRingFontScale,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilInnerRingSpacingMultiplier(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilInnerRingSpacingMultiplier,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilScaleSource(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilScaleSource,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilScaleMultiplier(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilScaleMultiplier,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilColorSource(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilColorSource,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilColorMultiplier(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilColorMultiplier,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setOilWoodstockEveryHour(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setOilWoodstockEveryHour,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setOilEkgRadius(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilEkgRadius,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilEkgReplication(int? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilEkgReplication,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleFilterHighestShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleFilterHighestShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setSourceCategoryFilter(
    String? category,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSourceCategoryFilter,
          [
            category,
            isActive,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setSoloSourceCategoryFilter(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSoloSourceCategoryFilter,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> enableAllSourceCategories() => (super.noSuchMethod(
        Invocation.method(
          #enableAllSourceCategories,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilTrackLetterSpacing(double? val) => (super.noSuchMethod(
        Invocation.method(
          #setOilTrackLetterSpacing,
          [val],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setOilTrackWordSpacing(double? val) => (super.noSuchMethod(
        Invocation.method(
          #setOilTrackWordSpacing,
          [val],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioProvider extends _i1.Mock implements _i8.AudioProvider {
  @override
  _i2.GaplessPlayer get audioPlayer => (super.noSuchMethod(
        Invocation.getter(#audioPlayer),
        returnValue: _FakeGaplessPlayer_0(
          this,
          Invocation.getter(#audioPlayer),
        ),
        returnValueForMissingStub: _FakeGaplessPlayer_0(
          this,
          Invocation.getter(#audioPlayer),
        ),
      ) as _i2.GaplessPlayer);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Stream<_i9.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i6.Stream<_i9.PlayerState>.empty(),
        returnValueForMissingStub: _i6.Stream<_i9.PlayerState>.empty(),
      ) as _i6.Stream<_i9.PlayerState>);

  @override
  _i6.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i6.Stream<int?>.empty(),
        returnValueForMissingStub: _i6.Stream<int?>.empty(),
      ) as _i6.Stream<int?>);

  @override
  _i6.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i6.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i6.Stream<Duration?>.empty(),
      ) as _i6.Stream<Duration?>);

  @override
  _i6.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i6.Stream<Duration>.empty(),
        returnValueForMissingStub: _i6.Stream<Duration>.empty(),
      ) as _i6.Stream<Duration>);

  @override
  _i6.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i6.Stream<Duration>.empty(),
        returnValueForMissingStub: _i6.Stream<Duration>.empty(),
      ) as _i6.Stream<Duration>);

  @override
  _i6.Stream<Duration?> get nextTrackBufferedStream => (super.noSuchMethod(
        Invocation.getter(#nextTrackBufferedStream),
        returnValue: _i6.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i6.Stream<Duration?>.empty(),
      ) as _i6.Stream<Duration?>);

  @override
  _i6.Stream<Duration?> get nextTrackTotalStream => (super.noSuchMethod(
        Invocation.getter(#nextTrackTotalStream),
        returnValue: _i6.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i6.Stream<Duration?>.empty(),
      ) as _i6.Stream<Duration?>);

  @override
  _i6.Stream<String> get playbackErrorStream => (super.noSuchMethod(
        Invocation.getter(#playbackErrorStream),
        returnValue: _i6.Stream<String>.empty(),
        returnValueForMissingStub: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  _i6.Stream<({_i10.Show show, _i11.Source source})>
      get randomShowRequestStream => (super.noSuchMethod(
            Invocation.getter(#randomShowRequestStream),
            returnValue:
                _i6.Stream<({_i10.Show show, _i11.Source source})>.empty(),
            returnValueForMissingStub:
                _i6.Stream<({_i10.Show show, _i11.Source source})>.empty(),
          ) as _i6.Stream<({_i10.Show show, _i11.Source source})>);

  @override
  _i6.Stream<({String message, _i7.VoidCallback? retryAction})>
      get bufferAgentNotificationStream => (super.noSuchMethod(
            Invocation.getter(#bufferAgentNotificationStream),
            returnValue: _i6.Stream<
                ({String message, _i7.VoidCallback? retryAction})>.empty(),
            returnValueForMissingStub: _i6.Stream<
                ({String message, _i7.VoidCallback? retryAction})>.empty(),
          ) as _i6.Stream<({String message, _i7.VoidCallback? retryAction})>);

  @override
  _i6.Stream<String> get notificationStream => (super.noSuchMethod(
        Invocation.getter(#notificationStream),
        returnValue: _i6.Stream<String>.empty(),
        returnValueForMissingStub: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  _i6.Stream<void> get playbackFocusRequestStream => (super.noSuchMethod(
        Invocation.getter(#playbackFocusRequestStream),
        returnValue: _i6.Stream<void>.empty(),
        returnValueForMissingStub: _i6.Stream<void>.empty(),
      ) as _i6.Stream<void>);

  @override
  int get cachedTrackCount => (super.noSuchMethod(
        Invocation.getter(#cachedTrackCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clearPendingRandomShowRequest() => super.noSuchMethod(
        Invocation.method(
          #clearPendingRandomShowRequest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update(
    _i12.ShowListProvider? showListProvider,
    _i3.SettingsProvider? settingsProvider,
    _i13.AudioCacheService? audioCacheService,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            showListProvider,
            settingsProvider,
            audioCacheService,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  ({_i10.Show show, _i11.Source source})? pickRandomShow(
          {bool? filterBySearch = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickRandomShow,
          [],
          {#filterBySearch: filterBySearch},
        ),
        returnValueForMissingStub: null,
      ) as ({_i10.Show show, _i11.Source source})?);

  @override
  _i6.Future<_i10.Show?> playRandomShow({
    bool? filterBySearch = true,
    bool? animationOnly = false,
    bool? delayPlayback = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playRandomShow,
          [],
          {
            #filterBySearch: filterBySearch,
            #animationOnly: animationOnly,
            #delayPlayback: delayPlayback,
          },
        ),
        returnValue: _i6.Future<_i10.Show?>.value(),
        returnValueForMissingStub: _i6.Future<_i10.Show?>.value(),
      ) as _i6.Future<_i10.Show?>);

  @override
  _i6.Future<void> playPendingSelection() => (super.noSuchMethod(
        Invocation.method(
          #playPendingSelection,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> playSource(
    _i10.Show? show,
    _i11.Source? source, {
    int? initialIndex = 0,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playSource,
          [
            show,
            source,
          ],
          {
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> playFromShareString(String? shareString) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromShareString,
          [shareString],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> queueRandomShow() => (super.noSuchMethod(
        Invocation.method(
          #queueRandomShow,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void showNotification(String? message) => super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void requestPlaybackFocus() => super.noSuchMethod(
        Invocation.method(
          #requestPlaybackFocus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> stopAndClear() => (super.noSuchMethod(
        Invocation.method(
          #stopAndClear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> retryCurrentSource() => (super.noSuchMethod(
        Invocation.method(
          #retryCurrentSource,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void seekToTrack(int? localIndex) => super.noSuchMethod(
        Invocation.method(
          #seekToTrack,
          [localIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
