name: gdar_tv
publish_to: none
version: 1.3.24+234
environment:
  sdk: '^3.11.0'
resolution: workspace
dependencies:
  shakedown_core:
    path: ../../packages/shakedown_core
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  sliding_up_panel2: ^3.3.0+1
  scrollable_positioned_list: ^0.3.8
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  provider: ^6.1.5
  intl: ^0.20.2
  http: ^1.2.1
  package_info_plus: ^8.3.1
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "../../packages/shakedown_core/assets/images/gdar_icon.webp"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "../../packages/shakedown_core/assets/images/gdar_icon_forground.webp"

flutter:
  uses-material-design: true

