name: gdar_fruit
environment:
  sdk: '^3.11.0'
resolution: workspace
dependencies:
  shakedown_core:
    path: ../../packages/shakedown_core
flutter:
  assets:
    - packages/shakedown_core/assets/data/output.optimized_src.json