// Mocks generated by Mockito 5.4.4 from annotations
// in shakedown/test/providers/audio_provider_regression_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i12;

import 'package:audio_session/audio_session.dart' as _i6;
import 'package:flutter/foundation.dart' as _i3;
import 'package:hive_flutter/hive_flutter.dart' as _i14;
import 'package:just_audio/just_audio.dart' as _i2;
import 'package:just_audio_background/just_audio_background.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:shakedown/models/rating.dart' as _i15;
import 'package:shakedown/models/show.dart' as _i8;
import 'package:shakedown/models/source.dart' as _i11;
import 'package:shakedown/providers/settings_provider.dart' as _i10;
import 'package:shakedown/providers/show_list_provider.dart' as _i7;
import 'package:shakedown/services/audio_cache_service.dart' as _i16;
import 'package:shakedown/services/catalog_service.dart' as _i13;
import 'package:shared_preferences/shared_preferences.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlayerEvent_0 extends _i1.SmartFake implements _i2.PlayerEvent {
  _FakePlayerEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaybackEvent_1 extends _i1.SmartFake implements _i2.PlaybackEvent {
  _FakePlaybackEvent_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_3 extends _i1.SmartFake implements _i2.PlayerState {
  _FakePlayerState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSequenceState_4 extends _i1.SmartFake implements _i2.SequenceState {
  _FakeSequenceState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_5<T> extends _i1.SmartFake
    implements _i3.ValueListenable<T> {
  _FakeValueListenable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioSource_6 extends _i1.SmartFake implements _i2.AudioSource {
  _FakeAudioSource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerRelaxed extends _i1.Mock implements _i2.AudioPlayer {
  @override
  _i2.PlayerEvent get playerEvent => (super.noSuchMethod(
        Invocation.getter(#playerEvent),
        returnValue: _FakePlayerEvent_0(
          this,
          Invocation.getter(#playerEvent),
        ),
        returnValueForMissingStub: _FakePlayerEvent_0(
          this,
          Invocation.getter(#playerEvent),
        ),
      ) as _i2.PlayerEvent);

  @override
  _i4.Stream<_i2.PlayerEvent> get playerEventStream => (super.noSuchMethod(
        Invocation.getter(#playerEventStream),
        returnValue: _i4.Stream<_i2.PlayerEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.PlayerEvent>.empty(),
      ) as _i4.Stream<_i2.PlayerEvent>);

  @override
  _i2.PlaybackEvent get playbackEvent => (super.noSuchMethod(
        Invocation.getter(#playbackEvent),
        returnValue: _FakePlaybackEvent_1(
          this,
          Invocation.getter(#playbackEvent),
        ),
        returnValueForMissingStub: _FakePlaybackEvent_1(
          this,
          Invocation.getter(#playbackEvent),
        ),
      ) as _i2.PlaybackEvent);

  @override
  _i4.Stream<_i2.PlaybackEvent> get playbackEventStream => (super.noSuchMethod(
        Invocation.getter(#playbackEventStream),
        returnValue: _i4.Stream<_i2.PlaybackEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.PlaybackEvent>.empty(),
      ) as _i4.Stream<_i2.PlaybackEvent>);

  @override
  _i4.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i4.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration?>.empty(),
      ) as _i4.Stream<Duration?>);

  @override
  _i2.ProcessingState get processingState => (super.noSuchMethod(
        Invocation.getter(#processingState),
        returnValue: _i2.ProcessingState.idle,
        returnValueForMissingStub: _i2.ProcessingState.idle,
      ) as _i2.ProcessingState);

  @override
  _i4.Stream<_i2.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i4.Stream<_i2.ProcessingState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.ProcessingState>.empty(),
      ) as _i4.Stream<_i2.ProcessingState>);

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<bool> get playingStream => (super.noSuchMethod(
        Invocation.getter(#playingStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get volumeStream => (super.noSuchMethod(
        Invocation.getter(#volumeStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  double get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get speedStream => (super.noSuchMethod(
        Invocation.getter(#speedStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  double get pitch => (super.noSuchMethod(
        Invocation.getter(#pitch),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get pitchStream => (super.noSuchMethod(
        Invocation.getter(#pitchStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  bool get skipSilenceEnabled => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<bool> get skipSilenceEnabledStream => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabledStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  Duration get bufferedPosition => (super.noSuchMethod(
        Invocation.getter(#bufferedPosition),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#bufferedPosition),
        ),
        returnValueForMissingStub: _FakeDuration_2(
          this,
          Invocation.getter(#bufferedPosition),
        ),
      ) as Duration);

  @override
  _i4.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<_i2.IcyMetadata?> get icyMetadataStream => (super.noSuchMethod(
        Invocation.getter(#icyMetadataStream),
        returnValue: _i4.Stream<_i2.IcyMetadata?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.IcyMetadata?>.empty(),
      ) as _i4.Stream<_i2.IcyMetadata?>);

  @override
  _i2.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _FakePlayerState_3(
          this,
          Invocation.getter(#playerState),
        ),
        returnValueForMissingStub: _FakePlayerState_3(
          this,
          Invocation.getter(#playerState),
        ),
      ) as _i2.PlayerState);

  @override
  _i4.Stream<_i2.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i4.Stream<_i2.PlayerState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.PlayerState>.empty(),
      ) as _i4.Stream<_i2.PlayerState>);

  @override
  List<_i2.IndexedAudioSource> get sequence => (super.noSuchMethod(
        Invocation.getter(#sequence),
        returnValue: <_i2.IndexedAudioSource>[],
        returnValueForMissingStub: <_i2.IndexedAudioSource>[],
      ) as List<_i2.IndexedAudioSource>);

  @override
  _i4.Stream<List<_i2.IndexedAudioSource>> get sequenceStream =>
      (super.noSuchMethod(
        Invocation.getter(#sequenceStream),
        returnValue: _i4.Stream<List<_i2.IndexedAudioSource>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<_i2.IndexedAudioSource>>.empty(),
      ) as _i4.Stream<List<_i2.IndexedAudioSource>>);

  @override
  List<int> get shuffleIndices => (super.noSuchMethod(
        Invocation.getter(#shuffleIndices),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i4.Stream<List<int>> get shuffleIndicesStream => (super.noSuchMethod(
        Invocation.getter(#shuffleIndicesStream),
        returnValue: _i4.Stream<List<int>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<int>>.empty(),
      ) as _i4.Stream<List<int>>);

  @override
  _i4.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i4.Stream<int?>.empty(),
        returnValueForMissingStub: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i2.SequenceState get sequenceState => (super.noSuchMethod(
        Invocation.getter(#sequenceState),
        returnValue: _FakeSequenceState_4(
          this,
          Invocation.getter(#sequenceState),
        ),
        returnValueForMissingStub: _FakeSequenceState_4(
          this,
          Invocation.getter(#sequenceState),
        ),
      ) as _i2.SequenceState);

  @override
  _i4.Stream<_i2.SequenceState> get sequenceStateStream => (super.noSuchMethod(
        Invocation.getter(#sequenceStateStream),
        returnValue: _i4.Stream<_i2.SequenceState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.SequenceState>.empty(),
      ) as _i4.Stream<_i2.SequenceState>);

  @override
  bool get hasNext => (super.noSuchMethod(
        Invocation.getter(#hasNext),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasPrevious => (super.noSuchMethod(
        Invocation.getter(#hasPrevious),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<int> get effectiveIndices => (super.noSuchMethod(
        Invocation.getter(#effectiveIndices),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.LoopMode get loopMode => (super.noSuchMethod(
        Invocation.getter(#loopMode),
        returnValue: _i2.LoopMode.off,
        returnValueForMissingStub: _i2.LoopMode.off,
      ) as _i2.LoopMode);

  @override
  _i4.Stream<_i2.LoopMode> get loopModeStream => (super.noSuchMethod(
        Invocation.getter(#loopModeStream),
        returnValue: _i4.Stream<_i2.LoopMode>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.LoopMode>.empty(),
      ) as _i4.Stream<_i2.LoopMode>);

  @override
  bool get shuffleModeEnabled => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<bool> get shuffleModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabledStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<int?> get androidAudioSessionIdStream => (super.noSuchMethod(
        Invocation.getter(#androidAudioSessionIdStream),
        returnValue: _i4.Stream<int?>.empty(),
        returnValueForMissingStub: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<_i2.PlayerException> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i4.Stream<_i2.PlayerException>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.PlayerException>.empty(),
      ) as _i4.Stream<_i2.PlayerException>);

  @override
  _i4.Stream<_i2.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
        Invocation.getter(#positionDiscontinuityStream),
        returnValue: _i4.Stream<_i2.PositionDiscontinuity>.empty(),
        returnValueForMissingStub:
            _i4.Stream<_i2.PositionDiscontinuity>.empty(),
      ) as _i4.Stream<_i2.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling => (super.noSuchMethod(
        Invocation.getter(#automaticallyWaitsToMinimizeStalling),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
        Invocation.getter(#canUseNetworkResourcesForLiveStreamingWhilePaused),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get preferredPeakBitRate => (super.noSuchMethod(
        Invocation.getter(#preferredPeakBitRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get allowsExternalPlayback => (super.noSuchMethod(
        Invocation.getter(#allowsExternalPlayback),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get webSinkId => (super.noSuchMethod(
        Invocation.getter(#webSinkId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
      ) as String);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#position),
        ),
        returnValueForMissingStub: _FakeDuration_2(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  _i4.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  List<_i2.AudioSource> get audioSources => (super.noSuchMethod(
        Invocation.getter(#audioSources),
        returnValue: <_i2.AudioSource>[],
        returnValueForMissingStub: <_i2.AudioSource>[],
      ) as List<_i2.AudioSource>);

  @override
  _i4.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPositionStream,
          [],
          {
            #steps: steps,
            #minPeriod: minPeriod,
            #maxPeriod: maxPeriod,
          },
        ),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUrl,
          [url],
          {
            #headers: headers,
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilePath,
          [filePath],
          {
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAsset,
          [assetPath],
          {
            #package: package,
            #preload: preload,
            #initialPosition: initialPosition,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAudioSource(
    _i2.AudioSource? audioSource, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [audioSource],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAudioSources(
    List<_i2.AudioSource>? audioSources, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
    _i2.ShuffleOrder? shuffleOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSources,
          [audioSources],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
            #shuffleOrder: shuffleOrder,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> addAudioSource(_i2.AudioSource? audioSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAudioSource,
          [audioSource],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertAudioSource(
    int? index,
    _i2.AudioSource? audioSource,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAudioSource,
          [
            index,
            audioSource,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addAudioSources(List<_i2.AudioSource>? audioSources) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAudioSources,
          [audioSources],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertAudioSources(
    int? index,
    List<_i2.AudioSource>? audioSources,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAudioSources,
          [
            index,
            audioSources,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeAudioSourceAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAudioSourceAt,
          [index],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeAudioSourceRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAudioSourceRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> moveAudioSource(
    int? currentIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveAudioSource,
          [
            currentIndex,
            newIndex,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAudioSources() => (super.noSuchMethod(
        Invocation.method(
          #clearAudioSources,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClip,
          [],
          {
            #start: start,
            #end: end,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSkipSilenceEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setSkipSilenceEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLoopMode(_i2.LoopMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setLoopMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setShuffleModeEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setShuffleModeEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> shuffle() => (super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAutomaticallyWaitsToMinimizeStalling(
          bool? automaticallyWaitsToMinimizeStalling) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutomaticallyWaitsToMinimizeStalling,
          [automaticallyWaitsToMinimizeStalling],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
          bool? canUseNetworkResourcesForLiveStreamingWhilePaused) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
          [canUseNetworkResourcesForLiveStreamingWhilePaused],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredPeakBitRate,
          [preferredPeakBitRate],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAllowsExternalPlayback,
          [allowsExternalPlayback],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seek(
    Duration? position, {
    int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
          {#index: index},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAndroidAudioAttributes(
          _i6.AndroidAudioAttributes? audioAttributes) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAndroidAudioAttributes,
          [audioAttributes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWebCrossOrigin(_i2.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWebCrossOrigin,
          [webCrossOrigin],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWebSinkId(String? webSinkId) => (super.noSuchMethod(
        Invocation.method(
          #setWebSinkId,
          [webSinkId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ShowListProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowListProvider extends _i1.Mock implements _i7.ShowListProvider {
  @override
  _i4.Future<void> get initializationComplete => (super.noSuchMethod(
        Invocation.getter(#initializationComplete),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  List<_i8.Show> get allShows => (super.noSuchMethod(
        Invocation.getter(#allShows),
        returnValue: <_i8.Show>[],
        returnValueForMissingStub: <_i8.Show>[],
      ) as List<_i8.Show>);

  @override
  bool get isArchiveReachable => (super.noSuchMethod(
        Invocation.getter(#isArchiveReachable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasCheckedArchive => (super.noSuchMethod(
        Invocation.getter(#hasCheckedArchive),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasUsedRandomButton => (super.noSuchMethod(
        Invocation.getter(#hasUsedRandomButton),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSearchVisible => (super.noSuchMethod(
        Invocation.getter(#isSearchVisible),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isChoosingRandomShow => (super.noSuchMethod(
        Invocation.getter(#isChoosingRandomShow),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get totalShnids => (super.noSuchMethod(
        Invocation.getter(#totalShnids),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<_i8.Show> get filteredShows => (super.noSuchMethod(
        Invocation.getter(#filteredShows),
        returnValue: <_i8.Show>[],
        returnValueForMissingStub: <_i8.Show>[],
      ) as List<_i8.Show>);

  @override
  Set<String> get availableCategories => (super.noSuchMethod(
        Invocation.getter(#availableCategories),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setSearchVisible(bool? visible) => super.noSuchMethod(
        Invocation.method(
          #setSearchVisible,
          [visible],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSearchVisible() => super.noSuchMethod(
        Invocation.method(
          #toggleSearchVisible,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markRandomButtonUsed() => super.noSuchMethod(
        Invocation.method(
          #markRandomButtonUsed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setIsChoosingRandomShow(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setIsChoosingRandomShow,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getShowKey(_i8.Show? show) => (super.noSuchMethod(
        Invocation.method(
          #getShowKey,
          [show],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getShowKey,
            [show],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getShowKey,
            [show],
          ),
        ),
      ) as String);

  @override
  void setArchiveStatus(bool? isReachable) => super.noSuchMethod(
        Invocation.method(
          #setArchiveStatus,
          [isReachable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init(_i9.SharedPreferences? prefs) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [prefs],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void update(_i10.SettingsProvider? settings) => super.noSuchMethod(
        Invocation.method(
          #update,
          [settings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Show? getShow(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getShow,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as _i8.Show?);

  @override
  bool isSourceAllowed(_i11.Source? source) => (super.noSuchMethod(
        Invocation.method(
          #isSourceAllowed,
          [source],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setPlayingShow(
    String? showName,
    String? sourceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlayingShow,
          [
            showName,
            sourceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> fetchShows(_i9.SharedPreferences? prefs) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchShows,
          [prefs],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkArchiveStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkArchiveStatus,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isShowExpanded(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isShowExpanded,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isShowLoading(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isShowLoading,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void toggleShowExpansion(String? key) => super.noSuchMethod(
        Invocation.method(
          #toggleShowExpansion,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadingShow(String? key) => super.noSuchMethod(
        Invocation.method(
          #setLoadingShow,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void expandShow(String? key) => super.noSuchMethod(
        Invocation.method(
          #expandShow,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void collapseCurrentShow() => super.noSuchMethod(
        Invocation.method(
          #collapseCurrentShow,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dismissShow(_i8.Show? show) => super.noSuchMethod(
        Invocation.method(
          #dismissShow,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dismissSource(
    _i8.Show? show,
    String? sourceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #dismissSource,
          [
            show,
            sourceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i10.SettingsProvider {
  @override
  bool get showExpandIcon => (super.noSuchMethod(
        Invocation.getter(#showExpandIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set showExpandIcon(bool? _showExpandIcon) => super.noSuchMethod(
        Invocation.setter(
          #showExpandIcon,
          _showExpandIcon,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get appFont => (super.noSuchMethod(
        Invocation.getter(#appFont),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#appFont),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#appFont),
        ),
      ) as String);

  @override
  bool get showSplashScreen => (super.noSuchMethod(
        Invocation.getter(#showSplashScreen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isFirstRun => (super.noSuchMethod(
        Invocation.getter(#isFirstRun),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showOnboarding => (super.noSuchMethod(
        Invocation.getter(#showOnboarding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showTrackNumbers => (super.noSuchMethod(
        Invocation.getter(#showTrackNumbers),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideTrackDuration => (super.noSuchMethod(
        Invocation.getter(#hideTrackDuration),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playOnTap => (super.noSuchMethod(
        Invocation.getter(#playOnTap),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showSingleShnid => (super.noSuchMethod(
        Invocation.getter(#showSingleShnid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideTrackCountInSourceList => (super.noSuchMethod(
        Invocation.getter(#hideTrackCountInSourceList),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playRandomOnCompletion => (super.noSuchMethod(
        Invocation.getter(#playRandomOnCompletion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get nonRandom => (super.noSuchMethod(
        Invocation.getter(#nonRandom),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playRandomOnStartup => (super.noSuchMethod(
        Invocation.getter(#playRandomOnStartup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get dateFirstInShowCard => (super.noSuchMethod(
        Invocation.getter(#dateFirstInShowCard),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useDynamicColor => (super.noSuchMethod(
        Invocation.getter(#useDynamicColor),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useTrueBlack => (super.noSuchMethod(
        Invocation.getter(#useTrueBlack),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useSliverAppBar => (super.noSuchMethod(
        Invocation.getter(#useSliverAppBar),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useSharedAxisTransition => (super.noSuchMethod(
        Invocation.getter(#useSharedAxisTransition),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get uiScale => (super.noSuchMethod(
        Invocation.getter(#uiScale),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get glowMode => (super.noSuchMethod(
        Invocation.getter(#glowMode),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get highlightPlayingWithRgb => (super.noSuchMethod(
        Invocation.getter(#highlightPlayingWithRgb),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showPlaybackMessages => (super.noSuchMethod(
        Invocation.getter(#showPlaybackMessages),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get sortOldestFirst => (super.noSuchMethod(
        Invocation.getter(#sortOldestFirst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useStrictSrcCategorization => (super.noSuchMethod(
        Invocation.getter(#useStrictSrcCategorization),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get offlineBuffering => (super.noSuchMethod(
        Invocation.getter(#offlineBuffering),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableBufferAgent => (super.noSuchMethod(
        Invocation.getter(#enableBufferAgent),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get preventScreensaver => (super.noSuchMethod(
        Invocation.getter(#preventScreensaver),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get highlightCurrentShowCard => (super.noSuchMethod(
        Invocation.getter(#highlightCurrentShowCard),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useMaterial3 => (super.noSuchMethod(
        Invocation.getter(#useMaterial3),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#showDayOfWeek),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get abbreviateDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#abbreviateDayOfWeek),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get abbreviateMonth => (super.noSuchMethod(
        Invocation.getter(#abbreviateMonth),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get simpleRandomIcon => (super.noSuchMethod(
        Invocation.getter(#simpleRandomIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get marqueeEnabled => (super.noSuchMethod(
        Invocation.getter(#marqueeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomOnlyUnplayed => (super.noSuchMethod(
        Invocation.getter(#randomOnlyUnplayed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomOnlyHighRated => (super.noSuchMethod(
        Invocation.getter(#randomOnlyHighRated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomExcludePlayed => (super.noSuchMethod(
        Invocation.getter(#randomExcludePlayed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showGlobalAlbumArt => (super.noSuchMethod(
        Invocation.getter(#showGlobalAlbumArt),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasShownAdvancedCacheSuggestion => (super.noSuchMethod(
        Invocation.getter(#hasShownAdvancedCacheSuggestion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDebugLayout => (super.noSuchMethod(
        Invocation.getter(#showDebugLayout),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableShakedownTween => (super.noSuchMethod(
        Invocation.getter(#enableShakedownTween),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get rgbAnimationSpeed => (super.noSuchMethod(
        Invocation.getter(#rgbAnimationSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get filterHighestShnid => (super.noSuchMethod(
        Invocation.getter(#filterHighestShnid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, bool> get sourceCategoryFilters => (super.noSuchMethod(
        Invocation.getter(#sourceCategoryFilters),
        returnValue: <String, bool>{},
        returnValueForMissingStub: <String, bool>{},
      ) as Map<String, bool>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setAppFont(String? font) => super.noSuchMethod(
        Invocation.method(
          #setAppFont,
          [font],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> completeOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleShowSplashScreen() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSplashScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markAdvancedCacheSuggestionShown() => super.noSuchMethod(
        Invocation.method(
          #markAdvancedCacheSuggestionShown,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDebugLayout() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDebugLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableShakedownTween() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableShakedownTween,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowTrackNumbers() => super.noSuchMethod(
        Invocation.method(
          #toggleShowTrackNumbers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHideTrackDuration() => super.noSuchMethod(
        Invocation.method(
          #toggleHideTrackDuration,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayOnTap() => super.noSuchMethod(
        Invocation.method(
          #togglePlayOnTap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowSingleShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSingleShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnCompletion() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnCompletion,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleNonRandom() => super.noSuchMethod(
        Invocation.method(
          #toggleNonRandom,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnStartup() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnStartup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleDateFirstInShowCard() => super.noSuchMethod(
        Invocation.method(
          #toggleDateFirstInShowCard,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseDynamicColor() => super.noSuchMethod(
        Invocation.method(
          #toggleUseDynamicColor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseTrueBlack() => super.noSuchMethod(
        Invocation.method(
          #toggleUseTrueBlack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDayOfWeek() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDayOfWeek,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAbbreviateDayOfWeek() => super.noSuchMethod(
        Invocation.method(
          #toggleAbbreviateDayOfWeek,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAbbreviateMonth() => super.noSuchMethod(
        Invocation.method(
          #toggleAbbreviateMonth,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSimpleRandomIcon() => super.noSuchMethod(
        Invocation.method(
          #toggleSimpleRandomIcon,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUiScale() => super.noSuchMethod(
        Invocation.method(
          #toggleUiScale,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGlowMode(int? mode) => super.noSuchMethod(
        Invocation.method(
          #setGlowMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHighlightPlayingWithRgb() => super.noSuchMethod(
        Invocation.method(
          #toggleHighlightPlayingWithRgb,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowPlaybackMessages() => super.noSuchMethod(
        Invocation.method(
          #toggleShowPlaybackMessages,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSortOldestFirst() => super.noSuchMethod(
        Invocation.method(
          #toggleSortOldestFirst,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseStrictSrcCategorization() => super.noSuchMethod(
        Invocation.method(
          #toggleUseStrictSrcCategorization,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOfflineBuffering() => super.noSuchMethod(
        Invocation.method(
          #toggleOfflineBuffering,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableBufferAgent() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableBufferAgent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePreventScreensaver() => super.noSuchMethod(
        Invocation.method(
          #togglePreventScreensaver,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRgbAnimationSpeed(double? speed) => super.noSuchMethod(
        Invocation.method(
          #setRgbAnimationSpeed,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setSeedColor(_i12.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #setSeedColor,
          [color],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleRandomOnlyUnplayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyUnplayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomOnlyHighRated() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyHighRated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomExcludePlayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomExcludePlayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFilterHighestShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleFilterHighestShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setSourceCategoryFilter(
    String? category,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSourceCategoryFilter,
          [
            category,
            isActive,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSoloSourceCategoryFilter(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSoloSourceCategoryFilter,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enableAllSourceCategories() => (super.noSuchMethod(
        Invocation.method(
          #enableAllSourceCategories,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CatalogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogService extends _i1.Mock implements _i13.CatalogService {
  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i8.Show> get allShows => (super.noSuchMethod(
        Invocation.getter(#allShows),
        returnValue: <_i8.Show>[],
        returnValueForMissingStub: <_i8.Show>[],
      ) as List<_i8.Show>);

  @override
  _i3.ValueListenable<_i14.Box<int>> get playCountsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#playCountsListenable),
        returnValue: _FakeValueListenable_5<_i14.Box<int>>(
          this,
          Invocation.getter(#playCountsListenable),
        ),
        returnValueForMissingStub: _FakeValueListenable_5<_i14.Box<int>>(
          this,
          Invocation.getter(#playCountsListenable),
        ),
      ) as _i3.ValueListenable<_i14.Box<int>>);

  @override
  _i3.ValueListenable<_i14.Box<bool>> get historyListenable =>
      (super.noSuchMethod(
        Invocation.getter(#historyListenable),
        returnValue: _FakeValueListenable_5<_i14.Box<bool>>(
          this,
          Invocation.getter(#historyListenable),
        ),
        returnValueForMissingStub: _FakeValueListenable_5<_i14.Box<bool>>(
          this,
          Invocation.getter(#historyListenable),
        ),
      ) as _i3.ValueListenable<_i14.Box<bool>>);

  @override
  _i3.ValueListenable<_i14.Box<_i15.Rating>> get ratingsListenable =>
      (super.noSuchMethod(
        Invocation.getter(#ratingsListenable),
        returnValue: _FakeValueListenable_5<_i14.Box<_i15.Rating>>(
          this,
          Invocation.getter(#ratingsListenable),
        ),
        returnValueForMissingStub:
            _FakeValueListenable_5<_i14.Box<_i15.Rating>>(
          this,
          Invocation.getter(#ratingsListenable),
        ),
      ) as _i3.ValueListenable<_i14.Box<_i15.Rating>>);

  @override
  _i4.Future<void> initialize({
    required _i9.SharedPreferences? prefs,
    _i13.CatalogLoadingStrategy? strategy =
        _i13.CatalogLoadingStrategy.inMemory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #prefs: prefs,
            #strategy: strategy,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> switchStrategy(_i13.CatalogLoadingStrategy? newStrategy) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchStrategy,
          [newStrategy],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRating(
    String? sourceId,
    int? ratingValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRating,
          [
            sourceId,
            ratingValue,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getRating(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #getRating,
          [sourceId],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i4.Future<void> incrementPlayCount(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #incrementPlayCount,
          [sourceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getPlayCount(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #getPlayCount,
          [sourceId],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool isPlayed(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #isPlayed,
          [sourceId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> markAsPlayed(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #markAsPlayed,
          [sourceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> togglePlayed(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #togglePlayed,
          [sourceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setRating(
    String? sourceId,
    int? rating,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            sourceId,
            rating,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AudioCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioCacheService extends _i1.Mock implements _i16.AudioCacheService {
  @override
  int get cachedTrackCount => (super.noSuchMethod(
        Invocation.getter(#cachedTrackCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AudioSource createAudioSource({
    required Uri? uri,
    required _i17.MediaItem? tag,
    required bool? useCache,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAudioSource,
          [],
          {
            #uri: uri,
            #tag: tag,
            #useCache: useCache,
          },
        ),
        returnValue: _FakeAudioSource_6(
          this,
          Invocation.method(
            #createAudioSource,
            [],
            {
              #uri: uri,
              #tag: tag,
              #useCache: useCache,
            },
          ),
        ),
        returnValueForMissingStub: _FakeAudioSource_6(
          this,
          Invocation.method(
            #createAudioSource,
            [],
            {
              #uri: uri,
              #tag: tag,
              #useCache: useCache,
            },
          ),
        ),
      ) as _i2.AudioSource);

  @override
  void monitorCache(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #monitorCache,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> refreshCacheCount() => (super.noSuchMethod(
        Invocation.method(
          #refreshCacheCount,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAudioCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAudioCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> performCacheCleanup({int? maxFiles = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performCacheCleanup,
          [],
          {#maxFiles: maxFiles},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> preloadSource(
    _i11.Source? source, {
    int? startIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #preloadSource,
          [source],
          {#startIndex: startIndex},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
