name: gdar_root
#resolution: workspace

environment:
  sdk: '^3.11.0'

workspace:
  - packages/shakedown_core
  - packages/screensaver_tv
  - packages/styles/*
  - apps/gdar_mobile
  - apps/gdar_tv
  - apps/gdar_web

dev_dependencies:
  shakedown_core:
    path: ./packages/shakedown_core
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  build_runner: ^2.4.8
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true
