import json
import os

# Use the output from the duration cleanup step as input
input_file = 'assets/data/output.cleaned_durations.json'
# Fallback
if not os.path.exists(input_file):
    input_file = 'assets/data/output.cleaned_encoding.json'

output_file = 'assets/data/output.cleaned_final.json'
report_file = 'final_encoding_cleanup_report.md'

target_strings = [
    # The Monster String (generated by diagnosis)
    # The Monster String (generated by diagnosis) - includes trailing ' to avoid double apostrophe
    'Ã\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â\x83Ã\x83Â\x83Ã\x82Â\x82Ã\x83Â\x82Ã\x82Â\x82Ã\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â\x82Ã\x83Â\x83Ã\x82Â\x82\'',
    
    # GoinÃ‚Â’ / ItÃ‚Â’s
    '\u00c3\u0082\u00c2\u0092', 
    
    # Uncle JohnÃ‚Â´s
    '\u00c3\u0082\u00c2\u00b4',

    # Shorter artifacts
    '\u00c2\u0092', 
    '\u00c2\u00b4', 
    '\u00c3\u0082', 
    '\ufffd' 
]
replacement = "'"

def main():
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found.")
        return

    print(f"Loading data from {input_file}...")
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    fixed_tracks = []
    
    print("Processing tracks...")
    for show in data:
        show_date = show.get('date', 'Unknown Date')
        for source in show.get('sources', []):
            source_id = source.get('id', 'Unknown ID')
            for s in source.get('sets', []):
                for t in s.get('t', []):
                    track_name = t.get('t', '')
                    
                    # Check for any of the target strings
                    found_target = False
                    for target in target_strings:
                        if target in track_name:
                            found_target = True
                            break
                    
                    if found_target:
                        original_name = track_name
                        new_name = track_name
                        for target in target_strings:
                            new_name = new_name.replace(target, replacement)
                        
                        t['t'] = new_name
                        
                        fixed_tracks.append({
                            'date': show_date,
                            'id': source_id,
                            'set': s.get('n', 'Unknown Set'),
                            'original': original_name,
                            'fixed': new_name
                        })

    # Save cleaned JSON
    print(f"Saving cleaned data to {output_file}...")
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, separators=(',', ':'))

    # Generate Report
    print(f"Generating report to {report_file}...")
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write("# Encoding Cleanup Report\n\n")
        f.write("## Targets Replaced\n")
        for target in target_strings:
            f.write(f"- `{target}` -> `{replacement}`\n")
        
        f.write(f"\nTotal tracks fixed: **{len(fixed_tracks)}**\n\n")
        
        f.write("## Fixed Tracks\n")
        f.write("| Date | Source ID | Set | Original Name | Fixed Name |\n")
        f.write("|---|---|---|---|---|\n")
        for item in fixed_tracks:
            # Escape pipes in names to avoid breaking markdown table
            orig = item['original'].replace('|', '\\|')
            fixed = item['fixed'].replace('|', '\\|')
            f.write(f"| {item['date']} | {item['id']} | {item['set']} | {orig} | {fixed} |\n")

    print(f"Cleanup complete. Fixed {len(fixed_tracks)} tracks.")

if __name__ == '__main__':
    main()
