// Mocks generated by Mockito 5.4.4 from annotations
// in shakedown/test/services/buffer_agent_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:just_audio/just_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shakedown/services/gapless_player/gapless_player_native.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_1 extends _i1.SmartFake implements _i2.PlayerState {
  _FakePlayerState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GaplessPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockGaplessPlayer extends _i1.Mock implements _i3.GaplessPlayer {
  MockGaplessPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
      ) as bool);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  Duration get bufferedPosition => (super.noSuchMethod(
        Invocation.getter(#bufferedPosition),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#bufferedPosition),
        ),
      ) as Duration);

  @override
  List<_i2.IndexedAudioSource> get sequence => (super.noSuchMethod(
        Invocation.getter(#sequence),
        returnValue: <_i2.IndexedAudioSource>[],
      ) as List<_i2.IndexedAudioSource>);

  @override
  _i2.ProcessingState get processingState => (super.noSuchMethod(
        Invocation.getter(#processingState),
        returnValue: _i2.ProcessingState.idle,
      ) as _i2.ProcessingState);

  @override
  _i2.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _FakePlayerState_1(
          this,
          Invocation.getter(#playerState),
        ),
      ) as _i2.PlayerState);

  @override
  _i4.Stream<_i2.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i4.Stream<_i2.PlayerState>.empty(),
      ) as _i4.Stream<_i2.PlayerState>);

  @override
  _i4.Stream<_i2.PlaybackEvent> get playbackEventStream => (super.noSuchMethod(
        Invocation.getter(#playbackEventStream),
        returnValue: _i4.Stream<_i2.PlaybackEvent>.empty(),
      ) as _i4.Stream<_i2.PlaybackEvent>);

  @override
  _i4.Stream<bool> get playingStream => (super.noSuchMethod(
        Invocation.getter(#playingStream),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<_i2.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i4.Stream<_i2.ProcessingState>.empty(),
      ) as _i4.Stream<_i2.ProcessingState>);

  @override
  _i4.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i4.Stream<Duration?>.empty(),
      ) as _i4.Stream<Duration?>);

  @override
  _i4.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<_i2.SequenceState?> get sequenceStateStream => (super.noSuchMethod(
        Invocation.getter(#sequenceStateStream),
        returnValue: _i4.Stream<_i2.SequenceState?>.empty(),
      ) as _i4.Stream<_i2.SequenceState?>);

  @override
  _i4.Future<Duration?> setAudioSources(
    List<_i2.AudioSource>? children, {
    int? initialIndex = 0,
    Duration? initialPosition = Duration.zero,
    bool? preload = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSources,
          [children],
          {
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
            #preload: preload,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> addAudioSources(List<_i2.AudioSource>? sources) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAudioSources,
          [sources],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seek(
    Duration? position, {
    int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
          {#index: index},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setWebPrefetchSeconds(int? seconds) => super.noSuchMethod(
        Invocation.method(
          #setWebPrefetchSeconds,
          [seconds],
        ),
        returnValueForMissingStub: null,
      );
}
