// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:shakedown_core/models/rating.dart';
import 'package:shakedown_core/models/show.dart';
import 'package:shakedown_core/models/source.dart';
import 'package:shakedown_core/models/track.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(RatingAdapter());
    registerAdapter(ShowAdapter());
    registerAdapter(SourceAdapter());
    registerAdapter(TrackAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(RatingAdapter());
    registerAdapter(ShowAdapter());
    registerAdapter(SourceAdapter());
    registerAdapter(TrackAdapter());
  }
}
