// Mocks generated by Mockito 5.4.4 from annotations
// in shakedown/test/screens/splash_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:just_audio/just_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:shakedown/models/show.dart' as _i6;
import 'package:shakedown/models/source.dart' as _i9;
import 'package:shakedown/providers/audio_provider.dart' as _i11;
import 'package:shakedown/providers/settings_provider.dart' as _i8;
import 'package:shakedown/providers/show_list_provider.dart' as _i3;
import 'package:shakedown/providers/update_provider.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAudioPlayer_0 extends _i1.SmartFake implements _i2.AudioPlayer {
  _FakeAudioPlayer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShowListProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowListProvider extends _i1.Mock implements _i3.ShowListProvider {
  @override
  _i4.Future<void> get initializationComplete => (super.noSuchMethod(
        Invocation.getter(#initializationComplete),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  List<_i6.Show> get allShows => (super.noSuchMethod(
        Invocation.getter(#allShows),
        returnValue: <_i6.Show>[],
        returnValueForMissingStub: <_i6.Show>[],
      ) as List<_i6.Show>);

  @override
  bool get isArchiveReachable => (super.noSuchMethod(
        Invocation.getter(#isArchiveReachable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasCheckedArchive => (super.noSuchMethod(
        Invocation.getter(#hasCheckedArchive),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasUsedRandomButton => (super.noSuchMethod(
        Invocation.getter(#hasUsedRandomButton),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSearchVisible => (super.noSuchMethod(
        Invocation.getter(#isSearchVisible),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isChoosingRandomShow => (super.noSuchMethod(
        Invocation.getter(#isChoosingRandomShow),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get totalShnids => (super.noSuchMethod(
        Invocation.getter(#totalShnids),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  List<_i6.Show> get filteredShows => (super.noSuchMethod(
        Invocation.getter(#filteredShows),
        returnValue: <_i6.Show>[],
        returnValueForMissingStub: <_i6.Show>[],
      ) as List<_i6.Show>);

  @override
  Set<String> get availableCategories => (super.noSuchMethod(
        Invocation.getter(#availableCategories),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setSearchVisible(bool? visible) => super.noSuchMethod(
        Invocation.method(
          #setSearchVisible,
          [visible],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSearchVisible() => super.noSuchMethod(
        Invocation.method(
          #toggleSearchVisible,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markRandomButtonUsed() => super.noSuchMethod(
        Invocation.method(
          #markRandomButtonUsed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setIsChoosingRandomShow(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setIsChoosingRandomShow,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getShowKey(_i6.Show? show) => (super.noSuchMethod(
        Invocation.method(
          #getShowKey,
          [show],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getShowKey,
            [show],
          ),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getShowKey,
            [show],
          ),
        ),
      ) as String);

  @override
  void setArchiveStatus(bool? isReachable) => super.noSuchMethod(
        Invocation.method(
          #setArchiveStatus,
          [isReachable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init(_i7.SharedPreferences? prefs) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [prefs],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void update(_i8.SettingsProvider? settings) => super.noSuchMethod(
        Invocation.method(
          #update,
          [settings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Show? getShow(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getShow,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as _i6.Show?);

  @override
  bool isSourceAllowed(_i9.Source? source) => (super.noSuchMethod(
        Invocation.method(
          #isSourceAllowed,
          [source],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setPlayingShow(
    String? showName,
    String? sourceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlayingShow,
          [
            showName,
            sourceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> fetchShows(_i7.SharedPreferences? prefs) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchShows,
          [prefs],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkArchiveStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkArchiveStatus,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isShowExpanded(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isShowExpanded,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isShowLoading(String? key) => (super.noSuchMethod(
        Invocation.method(
          #isShowLoading,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void toggleShowExpansion(String? key) => super.noSuchMethod(
        Invocation.method(
          #toggleShowExpansion,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadingShow(String? key) => super.noSuchMethod(
        Invocation.method(
          #setLoadingShow,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void expandShow(String? key) => super.noSuchMethod(
        Invocation.method(
          #expandShow,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void collapseCurrentShow() => super.noSuchMethod(
        Invocation.method(
          #collapseCurrentShow,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dismissShow(_i6.Show? show) => super.noSuchMethod(
        Invocation.method(
          #dismissShow,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dismissSource(
    _i6.Show? show,
    String? sourceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #dismissSource,
          [
            show,
            sourceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i8.SettingsProvider {
  @override
  bool get isTv => (super.noSuchMethod(
        Invocation.getter(#isTv),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showExpandIcon => (super.noSuchMethod(
        Invocation.getter(#showExpandIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set showExpandIcon(bool? _showExpandIcon) => super.noSuchMethod(
        Invocation.setter(
          #showExpandIcon,
          _showExpandIcon,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get appFont => (super.noSuchMethod(
        Invocation.getter(#appFont),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#appFont),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#appFont),
        ),
      ) as String);

  @override
  bool get showSplashScreen => (super.noSuchMethod(
        Invocation.getter(#showSplashScreen),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isFirstRun => (super.noSuchMethod(
        Invocation.getter(#isFirstRun),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showOnboarding => (super.noSuchMethod(
        Invocation.getter(#showOnboarding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showTrackNumbers => (super.noSuchMethod(
        Invocation.getter(#showTrackNumbers),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideTrackDuration => (super.noSuchMethod(
        Invocation.getter(#hideTrackDuration),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playOnTap => (super.noSuchMethod(
        Invocation.getter(#playOnTap),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showSingleShnid => (super.noSuchMethod(
        Invocation.getter(#showSingleShnid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hideTrackCountInSourceList => (super.noSuchMethod(
        Invocation.getter(#hideTrackCountInSourceList),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playRandomOnCompletion => (super.noSuchMethod(
        Invocation.getter(#playRandomOnCompletion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get nonRandom => (super.noSuchMethod(
        Invocation.getter(#nonRandom),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get playRandomOnStartup => (super.noSuchMethod(
        Invocation.getter(#playRandomOnStartup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get dateFirstInShowCard => (super.noSuchMethod(
        Invocation.getter(#dateFirstInShowCard),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useDynamicColor => (super.noSuchMethod(
        Invocation.getter(#useDynamicColor),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useTrueBlack => (super.noSuchMethod(
        Invocation.getter(#useTrueBlack),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useSliverAppBar => (super.noSuchMethod(
        Invocation.getter(#useSliverAppBar),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useSharedAxisTransition => (super.noSuchMethod(
        Invocation.getter(#useSharedAxisTransition),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get uiScale => (super.noSuchMethod(
        Invocation.getter(#uiScale),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get glowMode => (super.noSuchMethod(
        Invocation.getter(#glowMode),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get highlightPlayingWithRgb => (super.noSuchMethod(
        Invocation.getter(#highlightPlayingWithRgb),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showPlaybackMessages => (super.noSuchMethod(
        Invocation.getter(#showPlaybackMessages),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get sortOldestFirst => (super.noSuchMethod(
        Invocation.getter(#sortOldestFirst),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useStrictSrcCategorization => (super.noSuchMethod(
        Invocation.getter(#useStrictSrcCategorization),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get offlineBuffering => (super.noSuchMethod(
        Invocation.getter(#offlineBuffering),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableBufferAgent => (super.noSuchMethod(
        Invocation.getter(#enableBufferAgent),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get preventSleep => (super.noSuchMethod(
        Invocation.getter(#preventSleep),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get highlightCurrentShowCard => (super.noSuchMethod(
        Invocation.getter(#highlightCurrentShowCard),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useMaterial3 => (super.noSuchMethod(
        Invocation.getter(#useMaterial3),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#showDayOfWeek),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get abbreviateDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#abbreviateDayOfWeek),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get abbreviateMonth => (super.noSuchMethod(
        Invocation.getter(#abbreviateMonth),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get simpleRandomIcon => (super.noSuchMethod(
        Invocation.getter(#simpleRandomIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get marqueeEnabled => (super.noSuchMethod(
        Invocation.getter(#marqueeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get useOilScreensaver => (super.noSuchMethod(
        Invocation.getter(#useOilScreensaver),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get oilScreensaverMode => (super.noSuchMethod(
        Invocation.getter(#oilScreensaverMode),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#oilScreensaverMode),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#oilScreensaverMode),
        ),
      ) as String);

  @override
  int get oilScreensaverInactivityMinutes => (super.noSuchMethod(
        Invocation.getter(#oilScreensaverInactivityMinutes),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  double get oilFlowSpeed => (super.noSuchMethod(
        Invocation.getter(#oilFlowSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilPulseIntensity => (super.noSuchMethod(
        Invocation.getter(#oilPulseIntensity),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  String get oilPalette => (super.noSuchMethod(
        Invocation.getter(#oilPalette),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#oilPalette),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#oilPalette),
        ),
      ) as String);

  @override
  double get oilFilmGrain => (super.noSuchMethod(
        Invocation.getter(#oilFilmGrain),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilHeatDrift => (super.noSuchMethod(
        Invocation.getter(#oilHeatDrift),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilEnableAudioReactivity => (super.noSuchMethod(
        Invocation.getter(#oilEnableAudioReactivity),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get oilPerformanceMode => (super.noSuchMethod(
        Invocation.getter(#oilPerformanceMode),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get oilPaletteCycle => (super.noSuchMethod(
        Invocation.getter(#oilPaletteCycle),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get oilPaletteTransitionSpeed => (super.noSuchMethod(
        Invocation.getter(#oilPaletteTransitionSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilAudioReactivityStrength => (super.noSuchMethod(
        Invocation.getter(#oilAudioReactivityStrength),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilAudioBassBoost => (super.noSuchMethod(
        Invocation.getter(#oilAudioBassBoost),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get oilAudioPeakDecay => (super.noSuchMethod(
        Invocation.getter(#oilAudioPeakDecay),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get oilShowInfoBanner => (super.noSuchMethod(
        Invocation.getter(#oilShowInfoBanner),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomOnlyUnplayed => (super.noSuchMethod(
        Invocation.getter(#randomOnlyUnplayed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomOnlyHighRated => (super.noSuchMethod(
        Invocation.getter(#randomOnlyHighRated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get randomExcludePlayed => (super.noSuchMethod(
        Invocation.getter(#randomExcludePlayed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showGlobalAlbumArt => (super.noSuchMethod(
        Invocation.getter(#showGlobalAlbumArt),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasShownAdvancedCacheSuggestion => (super.noSuchMethod(
        Invocation.getter(#hasShownAdvancedCacheSuggestion),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get showDebugLayout => (super.noSuchMethod(
        Invocation.getter(#showDebugLayout),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get enableShakedownTween => (super.noSuchMethod(
        Invocation.getter(#enableShakedownTween),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get rgbAnimationSpeed => (super.noSuchMethod(
        Invocation.getter(#rgbAnimationSpeed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get filterHighestShnid => (super.noSuchMethod(
        Invocation.getter(#filterHighestShnid),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, bool> get sourceCategoryFilters => (super.noSuchMethod(
        Invocation.getter(#sourceCategoryFilters),
        returnValue: <String, bool>{},
        returnValueForMissingStub: <String, bool>{},
      ) as Map<String, bool>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setAppFont(String? font) => super.noSuchMethod(
        Invocation.method(
          #setAppFont,
          [font],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> completeOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleShowSplashScreen() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSplashScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markAdvancedCacheSuggestionShown() => super.noSuchMethod(
        Invocation.method(
          #markAdvancedCacheSuggestionShown,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDebugLayout() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDebugLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableShakedownTween() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableShakedownTween,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowTrackNumbers() => super.noSuchMethod(
        Invocation.method(
          #toggleShowTrackNumbers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHideTrackDuration() => super.noSuchMethod(
        Invocation.method(
          #toggleHideTrackDuration,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayOnTap() => super.noSuchMethod(
        Invocation.method(
          #togglePlayOnTap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowSingleShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSingleShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnCompletion() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnCompletion,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleNonRandom() => super.noSuchMethod(
        Invocation.method(
          #toggleNonRandom,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnStartup() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnStartup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleDateFirstInShowCard() => super.noSuchMethod(
        Invocation.method(
          #toggleDateFirstInShowCard,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseDynamicColor() => super.noSuchMethod(
        Invocation.method(
          #toggleUseDynamicColor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseTrueBlack() => super.noSuchMethod(
        Invocation.method(
          #toggleUseTrueBlack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowDayOfWeek() => super.noSuchMethod(
        Invocation.method(
          #toggleShowDayOfWeek,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAbbreviateDayOfWeek() => super.noSuchMethod(
        Invocation.method(
          #toggleAbbreviateDayOfWeek,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAbbreviateMonth() => super.noSuchMethod(
        Invocation.method(
          #toggleAbbreviateMonth,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSimpleRandomIcon() => super.noSuchMethod(
        Invocation.method(
          #toggleSimpleRandomIcon,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUiScale() => super.noSuchMethod(
        Invocation.method(
          #toggleUiScale,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGlowMode(int? mode) => super.noSuchMethod(
        Invocation.method(
          #setGlowMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHighlightPlayingWithRgb() => super.noSuchMethod(
        Invocation.method(
          #toggleHighlightPlayingWithRgb,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowPlaybackMessages() => super.noSuchMethod(
        Invocation.method(
          #toggleShowPlaybackMessages,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSortOldestFirst() => super.noSuchMethod(
        Invocation.method(
          #toggleSortOldestFirst,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseStrictSrcCategorization() => super.noSuchMethod(
        Invocation.method(
          #toggleUseStrictSrcCategorization,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOfflineBuffering() => super.noSuchMethod(
        Invocation.method(
          #toggleOfflineBuffering,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleEnableBufferAgent() => super.noSuchMethod(
        Invocation.method(
          #toggleEnableBufferAgent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePreventSleep() => super.noSuchMethod(
        Invocation.method(
          #togglePreventSleep,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRgbAnimationSpeed(double? speed) => super.noSuchMethod(
        Invocation.method(
          #setRgbAnimationSpeed,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setSeedColor(_i10.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #setSeedColor,
          [color],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleRandomOnlyUnplayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyUnplayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomOnlyHighRated() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyHighRated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomExcludePlayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomExcludePlayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseOilScreensaver() => super.noSuchMethod(
        Invocation.method(
          #toggleUseOilScreensaver,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOilScreensaverMode(String? mode) => super.noSuchMethod(
        Invocation.method(
          #setOilScreensaverMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOilScreensaverInactivityMinutes(int? minutes) => super.noSuchMethod(
        Invocation.method(
          #setOilScreensaverInactivityMinutes,
          [minutes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setOilFlowSpeed(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilFlowSpeed,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOilPulseIntensity(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilPulseIntensity,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOilPalette(String? palette) => (super.noSuchMethod(
        Invocation.method(
          #setOilPalette,
          [palette],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOilFilmGrain(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilFilmGrain,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOilHeatDrift(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilHeatDrift,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleOilEnableAudioReactivity() => super.noSuchMethod(
        Invocation.method(
          #toggleOilEnableAudioReactivity,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOilPerformanceMode() => super.noSuchMethod(
        Invocation.method(
          #toggleOilPerformanceMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOilPaletteCycle() => super.noSuchMethod(
        Invocation.method(
          #toggleOilPaletteCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOilPaletteTransitionSpeed(double? seconds) => super.noSuchMethod(
        Invocation.method(
          #setOilPaletteTransitionSpeed,
          [seconds],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setOilAudioReactivityStrength(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOilAudioReactivityStrength,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOilAudioBassBoost(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilAudioBassBoost,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setOilAudioPeakDecay(double? value) => (super.noSuchMethod(
        Invocation.method(
          #setOilAudioPeakDecay,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleOilShowInfoBanner() => super.noSuchMethod(
        Invocation.method(
          #toggleOilShowInfoBanner,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFilterHighestShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleFilterHighestShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setSourceCategoryFilter(
    String? category,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSourceCategoryFilter,
          [
            category,
            isActive,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSoloSourceCategoryFilter(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSoloSourceCategoryFilter,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enableAllSourceCategories() => (super.noSuchMethod(
        Invocation.method(
          #enableAllSourceCategories,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioProvider extends _i1.Mock implements _i11.AudioProvider {
  @override
  _i2.AudioPlayer get audioPlayer => (super.noSuchMethod(
        Invocation.getter(#audioPlayer),
        returnValue: _FakeAudioPlayer_0(
          this,
          Invocation.getter(#audioPlayer),
        ),
        returnValueForMissingStub: _FakeAudioPlayer_0(
          this,
          Invocation.getter(#audioPlayer),
        ),
      ) as _i2.AudioPlayer);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<_i2.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i4.Stream<_i2.PlayerState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.PlayerState>.empty(),
      ) as _i4.Stream<_i2.PlayerState>);

  @override
  _i4.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i4.Stream<int?>.empty(),
        returnValueForMissingStub: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i4.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration?>.empty(),
      ) as _i4.Stream<Duration?>);

  @override
  _i4.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<String> get playbackErrorStream => (super.noSuchMethod(
        Invocation.getter(#playbackErrorStream),
        returnValue: _i4.Stream<String>.empty(),
        returnValueForMissingStub: _i4.Stream<String>.empty(),
      ) as _i4.Stream<String>);

  @override
  _i4.Stream<({_i6.Show show, _i9.Source source})>
      get randomShowRequestStream => (super.noSuchMethod(
            Invocation.getter(#randomShowRequestStream),
            returnValue:
                _i4.Stream<({_i6.Show show, _i9.Source source})>.empty(),
            returnValueForMissingStub:
                _i4.Stream<({_i6.Show show, _i9.Source source})>.empty(),
          ) as _i4.Stream<({_i6.Show show, _i9.Source source})>);

  @override
  _i4.Stream<({String message, _i10.VoidCallback? retryAction})>
      get bufferAgentNotificationStream => (super.noSuchMethod(
            Invocation.getter(#bufferAgentNotificationStream),
            returnValue: _i4.Stream<
                ({String message, _i10.VoidCallback? retryAction})>.empty(),
            returnValueForMissingStub: _i4.Stream<
                ({String message, _i10.VoidCallback? retryAction})>.empty(),
          ) as _i4.Stream<({String message, _i10.VoidCallback? retryAction})>);

  @override
  int get cachedTrackCount => (super.noSuchMethod(
        Invocation.getter(#cachedTrackCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void clearPendingRandomShowRequest() => super.noSuchMethod(
        Invocation.method(
          #clearPendingRandomShowRequest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update(
    _i3.ShowListProvider? showListProvider,
    _i8.SettingsProvider? settingsProvider,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            showListProvider,
            settingsProvider,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  ({_i6.Show show, _i9.Source source})? pickRandomShow(
          {bool? filterBySearch = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickRandomShow,
          [],
          {#filterBySearch: filterBySearch},
        ),
        returnValueForMissingStub: null,
      ) as ({_i6.Show show, _i9.Source source})?);

  @override
  _i4.Future<_i6.Show?> playRandomShow({
    bool? filterBySearch = true,
    bool? animationOnly = false,
    bool? delayPlayback = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playRandomShow,
          [],
          {
            #filterBySearch: filterBySearch,
            #animationOnly: animationOnly,
            #delayPlayback: delayPlayback,
          },
        ),
        returnValue: _i4.Future<_i6.Show?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.Show?>.value(),
      ) as _i4.Future<_i6.Show?>);

  @override
  _i4.Future<void> playPendingSelection() => (super.noSuchMethod(
        Invocation.method(
          #playPendingSelection,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> playSource(
    _i6.Show? show,
    _i9.Source? source, {
    int? initialIndex = 0,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playSource,
          [
            show,
            source,
          ],
          {
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> playFromShareString(String? shareString) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromShareString,
          [shareString],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> queueRandomShow() => (super.noSuchMethod(
        Invocation.method(
          #queueRandomShow,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> stopAndClear() => (super.noSuchMethod(
        Invocation.method(
          #stopAndClear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void play() => super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekToNext() => super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekToPrevious() => super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seek(Duration? position) => super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> retryCurrentSource() => (super.noSuchMethod(
        Invocation.method(
          #retryCurrentSource,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void seekToTrack(int? localIndex) => super.noSuchMethod(
        Invocation.method(
          #seekToTrack,
          [localIndex],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UpdateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProvider extends _i1.Mock implements _i12.UpdateProvider {
  @override
  bool get isSimulated => (super.noSuchMethod(
        Invocation.getter(#isSimulated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> checkForUpdate() => (super.noSuchMethod(
        Invocation.method(
          #checkForUpdate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startUpdate() => (super.noSuchMethod(
        Invocation.method(
          #startUpdate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void simulateUpdate() => super.noSuchMethod(
        Invocation.method(
          #simulateUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
