// Mocks generated by Mockito 5.4.6 from annotations
// in gdar/test/screens/splash_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:gdar/models/show.dart' as _i5;
import 'package:gdar/models/source.dart' as _i10;
import 'package:gdar/providers/audio_provider.dart' as _i9;
import 'package:gdar/providers/settings_provider.dart' as _i8;
import 'package:gdar/providers/show_list_provider.dart' as _i3;
import 'package:just_audio/just_audio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAudioPlayer_0 extends _i1.SmartFake implements _i2.AudioPlayer {
  _FakeAudioPlayer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShowListProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowListProvider extends _i1.Mock implements _i3.ShowListProvider {
  MockShowListProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  List<_i5.Show> get allShows => (super.noSuchMethod(
        Invocation.getter(#allShows),
        returnValue: <_i5.Show>[],
      ) as List<_i5.Show>);

  @override
  bool get isArchiveReachable => (super.noSuchMethod(
        Invocation.getter(#isArchiveReachable),
        returnValue: false,
      ) as bool);

  @override
  bool get hasCheckedArchive => (super.noSuchMethod(
        Invocation.getter(#hasCheckedArchive),
        returnValue: false,
      ) as bool);

  @override
  int get totalShnids => (super.noSuchMethod(
        Invocation.getter(#totalShnids),
        returnValue: 0,
      ) as int);

  @override
  List<_i5.Show> get filteredShows => (super.noSuchMethod(
        Invocation.getter(#filteredShows),
        returnValue: <_i5.Show>[],
      ) as List<_i5.Show>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setArchiveStatus(bool? isReachable) => super.noSuchMethod(
        Invocation.method(
          #setArchiveStatus,
          [isReachable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fetchShows() => (super.noSuchMethod(
        Invocation.method(
          #fetchShows,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> checkArchiveStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkArchiveStatus,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onShowTap(_i5.Show? show) => super.noSuchMethod(
        Invocation.method(
          #onShowTap,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadingShow(String? showName) => super.noSuchMethod(
        Invocation.method(
          #setLoadingShow,
          [showName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void expandShow(_i5.Show? show) => super.noSuchMethod(
        Invocation.method(
          #expandShow,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void collapseCurrentShow() => super.noSuchMethod(
        Invocation.method(
          #collapseCurrentShow,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i8.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get showSplashScreen => (super.noSuchMethod(
        Invocation.getter(#showSplashScreen),
        returnValue: false,
      ) as bool);

  @override
  bool get showExpandIcon => (super.noSuchMethod(
        Invocation.getter(#showExpandIcon),
        returnValue: false,
      ) as bool);

  @override
  bool get showTrackNumbers => (super.noSuchMethod(
        Invocation.getter(#showTrackNumbers),
        returnValue: false,
      ) as bool);

  @override
  bool get playOnTap => (super.noSuchMethod(
        Invocation.getter(#playOnTap),
        returnValue: false,
      ) as bool);

  @override
  bool get showSingleShnid => (super.noSuchMethod(
        Invocation.getter(#showSingleShnid),
        returnValue: false,
      ) as bool);

  @override
  bool get hideTrackCountInSourceList => (super.noSuchMethod(
        Invocation.getter(#hideTrackCountInSourceList),
        returnValue: false,
      ) as bool);

  @override
  bool get playRandomOnCompletion => (super.noSuchMethod(
        Invocation.getter(#playRandomOnCompletion),
        returnValue: false,
      ) as bool);

  @override
  bool get playRandomOnStartup => (super.noSuchMethod(
        Invocation.getter(#playRandomOnStartup),
        returnValue: false,
      ) as bool);

  @override
  bool get dateFirstInShowCard => (super.noSuchMethod(
        Invocation.getter(#dateFirstInShowCard),
        returnValue: false,
      ) as bool);

  @override
  bool get useDynamicColor => (super.noSuchMethod(
        Invocation.getter(#useDynamicColor),
        returnValue: false,
      ) as bool);

  @override
  bool get useSliverAppBar => (super.noSuchMethod(
        Invocation.getter(#useSliverAppBar),
        returnValue: false,
      ) as bool);

  @override
  bool get useSharedAxisTransition => (super.noSuchMethod(
        Invocation.getter(#useSharedAxisTransition),
        returnValue: false,
      ) as bool);

  @override
  bool get useHandwritingFont => (super.noSuchMethod(
        Invocation.getter(#useHandwritingFont),
        returnValue: false,
      ) as bool);

  @override
  bool get uiScale => (super.noSuchMethod(
        Invocation.getter(#uiScale),
        returnValue: false,
      ) as bool);

  @override
  bool get showGlowBorder => (super.noSuchMethod(
        Invocation.getter(#showGlowBorder),
        returnValue: false,
      ) as bool);

  @override
  bool get highlightPlayingWithRgb => (super.noSuchMethod(
        Invocation.getter(#highlightPlayingWithRgb),
        returnValue: false,
      ) as bool);

  @override
  bool get showPlaybackMessages => (super.noSuchMethod(
        Invocation.getter(#showPlaybackMessages),
        returnValue: false,
      ) as bool);

  @override
  bool get highlightCurrentShowCard => (super.noSuchMethod(
        Invocation.getter(#highlightCurrentShowCard),
        returnValue: false,
      ) as bool);

  @override
  bool get useMaterial3 => (super.noSuchMethod(
        Invocation.getter(#useMaterial3),
        returnValue: false,
      ) as bool);

  @override
  Map<String, int> get showRatings => (super.noSuchMethod(
        Invocation.getter(#showRatings),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  Set<String> get playedShows => (super.noSuchMethod(
        Invocation.getter(#playedShows),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  bool get randomOnlyUnplayed => (super.noSuchMethod(
        Invocation.getter(#randomOnlyUnplayed),
        returnValue: false,
      ) as bool);

  @override
  bool get randomOnlyHighRated => (super.noSuchMethod(
        Invocation.getter(#randomOnlyHighRated),
        returnValue: false,
      ) as bool);

  @override
  bool get halfGlowDynamic => (super.noSuchMethod(
        Invocation.getter(#halfGlowDynamic),
        returnValue: false,
      ) as bool);

  @override
  double get rgbAnimationSpeed => (super.noSuchMethod(
        Invocation.getter(#rgbAnimationSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  set showExpandIcon(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #showExpandIcon,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void toggleShowSplashScreen() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSplashScreen,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowTrackNumbers() => super.noSuchMethod(
        Invocation.method(
          #toggleShowTrackNumbers,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayOnTap() => super.noSuchMethod(
        Invocation.method(
          #togglePlayOnTap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowSingleShnid() => super.noSuchMethod(
        Invocation.method(
          #toggleShowSingleShnid,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnCompletion() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnCompletion,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlayRandomOnStartup() => super.noSuchMethod(
        Invocation.method(
          #togglePlayRandomOnStartup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleDateFirstInShowCard() => super.noSuchMethod(
        Invocation.method(
          #toggleDateFirstInShowCard,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseDynamicColor() => super.noSuchMethod(
        Invocation.method(
          #toggleUseDynamicColor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUseHandwritingFont() => super.noSuchMethod(
        Invocation.method(
          #toggleUseHandwritingFont,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleUiScale() => super.noSuchMethod(
        Invocation.method(
          #toggleUiScale,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowGlowBorder() => super.noSuchMethod(
        Invocation.method(
          #toggleShowGlowBorder,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHighlightPlayingWithRgb() => super.noSuchMethod(
        Invocation.method(
          #toggleHighlightPlayingWithRgb,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleShowPlaybackMessages() => super.noSuchMethod(
        Invocation.method(
          #toggleShowPlaybackMessages,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleHalfGlowDynamic() => super.noSuchMethod(
        Invocation.method(
          #toggleHalfGlowDynamic,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRgbAnimationSpeed(double? speed) => super.noSuchMethod(
        Invocation.method(
          #setRgbAnimationSpeed,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setSeedColor(_i7.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #setSeedColor,
          [color],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  int getRating(String? showName) => (super.noSuchMethod(
        Invocation.method(
          #getRating,
          [showName],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool isPlayed(String? showName) => (super.noSuchMethod(
        Invocation.method(
          #isPlayed,
          [showName],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> setRating(
    String? showName,
    int? rating,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            showName,
            rating,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> togglePlayed(String? showName) => (super.noSuchMethod(
        Invocation.method(
          #togglePlayed,
          [showName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markAsPlayed(String? showName) => (super.noSuchMethod(
        Invocation.method(
          #markAsPlayed,
          [showName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void toggleRandomOnlyUnplayed() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyUnplayed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRandomOnlyHighRated() => super.noSuchMethod(
        Invocation.method(
          #toggleRandomOnlyHighRated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioProvider extends _i1.Mock implements _i9.AudioProvider {
  MockAudioProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AudioPlayer get audioPlayer => (super.noSuchMethod(
        Invocation.getter(#audioPlayer),
        returnValue: _FakeAudioPlayer_0(
          this,
          Invocation.getter(#audioPlayer),
        ),
      ) as _i2.AudioPlayer);

  @override
  _i6.Stream<_i2.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i6.Stream<_i2.PlayerState>.empty(),
      ) as _i6.Stream<_i2.PlayerState>);

  @override
  _i6.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i6.Stream<int?>.empty(),
      ) as _i6.Stream<int?>);

  @override
  _i6.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i6.Stream<Duration?>.empty(),
      ) as _i6.Stream<Duration?>);

  @override
  _i6.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i6.Stream<Duration>.empty(),
      ) as _i6.Stream<Duration>);

  @override
  _i6.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i6.Stream<Duration>.empty(),
      ) as _i6.Stream<Duration>);

  @override
  _i6.Stream<String> get playbackErrorStream => (super.noSuchMethod(
        Invocation.getter(#playbackErrorStream),
        returnValue: _i6.Stream<String>.empty(),
      ) as _i6.Stream<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void update(
    _i3.ShowListProvider? showListProvider,
    _i8.SettingsProvider? settingsProvider,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            showListProvider,
            settingsProvider,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i5.Show?> playRandomShow() => (super.noSuchMethod(
        Invocation.method(
          #playRandomShow,
          [],
        ),
        returnValue: _i6.Future<_i5.Show?>.value(),
      ) as _i6.Future<_i5.Show?>);

  @override
  _i6.Future<void> playSource(
    _i5.Show? show,
    _i10.Source? source, {
    int? initialIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playSource,
          [
            show,
            source,
          ],
          {#initialIndex: initialIndex},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> stopAndClear() => (super.noSuchMethod(
        Invocation.method(
          #stopAndClear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void play() => super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekToNext() => super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekToPrevious() => super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seek(Duration? position) => super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void seekToTrack(int? index) => super.noSuchMethod(
        Invocation.method(
          #seekToTrack,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
