// Mocks generated by Mockito 5.4.6 from annotations
// in shakedown_core/test/screens/playback_screen_tv_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:just_audio/just_audio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shakedown_core/models/show.dart' as _i6;
import 'package:shakedown_core/models/source.dart' as _i7;
import 'package:shakedown_core/providers/audio_provider.dart' as _i4;
import 'package:shakedown_core/providers/settings_provider.dart' as _i10;
import 'package:shakedown_core/providers/show_list_provider.dart' as _i9;
import 'package:shakedown_core/services/audio_cache_service.dart' as _i11;
import 'package:shakedown_core/services/gapless_player/gapless_player.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGaplessPlayer_0 extends _i1.SmartFake implements _i2.GaplessPlayer {
  _FakeGaplessPlayer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerState_2 extends _i1.SmartFake implements _i3.PlayerState {
  _FakePlayerState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AudioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioProvider extends _i1.Mock implements _i4.AudioProvider {
  MockAudioProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GaplessPlayer get audioPlayer =>
      (super.noSuchMethod(
            Invocation.getter(#audioPlayer),
            returnValue: _FakeGaplessPlayer_0(
              this,
              Invocation.getter(#audioPlayer),
            ),
          )
          as _i2.GaplessPlayer);

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  _i5.Stream<_i3.PlayerState> get playerStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateStream),
            returnValue: _i5.Stream<_i3.PlayerState>.empty(),
          )
          as _i5.Stream<_i3.PlayerState>);

  @override
  _i5.Stream<int?> get currentIndexStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentIndexStream),
            returnValue: _i5.Stream<int?>.empty(),
          )
          as _i5.Stream<int?>);

  @override
  _i5.Stream<Duration?> get durationStream =>
      (super.noSuchMethod(
            Invocation.getter(#durationStream),
            returnValue: _i5.Stream<Duration?>.empty(),
          )
          as _i5.Stream<Duration?>);

  @override
  _i5.Stream<Duration> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i5.Stream<Duration>.empty(),
          )
          as _i5.Stream<Duration>);

  @override
  _i5.Stream<Duration> get bufferedPositionStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPositionStream),
            returnValue: _i5.Stream<Duration>.empty(),
          )
          as _i5.Stream<Duration>);

  @override
  _i5.Stream<Duration?> get nextTrackBufferedStream =>
      (super.noSuchMethod(
            Invocation.getter(#nextTrackBufferedStream),
            returnValue: _i5.Stream<Duration?>.empty(),
          )
          as _i5.Stream<Duration?>);

  @override
  _i5.Stream<Duration?> get nextTrackTotalStream =>
      (super.noSuchMethod(
            Invocation.getter(#nextTrackTotalStream),
            returnValue: _i5.Stream<Duration?>.empty(),
          )
          as _i5.Stream<Duration?>);

  @override
  _i5.Stream<bool> get heartbeatActiveStream =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatActiveStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> get heartbeatNeededStream =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatNeededStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<String> get engineStateStringStream =>
      (super.noSuchMethod(
            Invocation.getter(#engineStateStringStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<String> get engineContextStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#engineContextStateStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<String> get playbackErrorStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackErrorStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<({_i6.Show show, _i7.Source source})>
  get randomShowRequestStream =>
      (super.noSuchMethod(
            Invocation.getter(#randomShowRequestStream),
            returnValue:
                _i5.Stream<({_i6.Show show, _i7.Source source})>.empty(),
          )
          as _i5.Stream<({_i6.Show show, _i7.Source source})>);

  @override
  _i5.Stream<({String message, _i8.VoidCallback? retryAction})>
  get bufferAgentNotificationStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferAgentNotificationStream),
            returnValue:
                _i5.Stream<
                  ({String message, _i8.VoidCallback? retryAction})
                >.empty(),
          )
          as _i5.Stream<({String message, _i8.VoidCallback? retryAction})>);

  @override
  _i5.Stream<String> get notificationStream =>
      (super.noSuchMethod(
            Invocation.getter(#notificationStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<void> get playbackFocusRequestStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackFocusRequestStream),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  int get cachedTrackCount =>
      (super.noSuchMethod(Invocation.getter(#cachedTrackCount), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void clearPendingRandomShowRequest() => super.noSuchMethod(
    Invocation.method(#clearPendingRandomShowRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  void update(
    _i9.ShowListProvider? showListProvider,
    _i10.SettingsProvider? settingsProvider,
    _i11.AudioCacheService? audioCacheService,
  ) => super.noSuchMethod(
    Invocation.method(#update, [
      showListProvider,
      settingsProvider,
      audioCacheService,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  ({_i6.Show show, _i7.Source source})? pickRandomShow({
    bool? filterBySearch = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickRandomShow, [], {
              #filterBySearch: filterBySearch,
            }),
          )
          as ({_i6.Show show, _i7.Source source})?);

  @override
  _i5.Future<_i6.Show?> playRandomShow({
    bool? filterBySearch = true,
    bool? animationOnly = false,
    bool? delayPlayback = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#playRandomShow, [], {
              #filterBySearch: filterBySearch,
              #animationOnly: animationOnly,
              #delayPlayback: delayPlayback,
            }),
            returnValue: _i5.Future<_i6.Show?>.value(),
          )
          as _i5.Future<_i6.Show?>);

  @override
  _i5.Future<void> playPendingSelection() =>
      (super.noSuchMethod(
            Invocation.method(#playPendingSelection, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playSource(
    _i6.Show? show,
    _i7.Source? source, {
    int? initialIndex = 0,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #playSource,
              [show, source],
              {#initialIndex: initialIndex, #initialPosition: initialPosition},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> playFromShareString(String? shareString) =>
      (super.noSuchMethod(
            Invocation.method(#playFromShareString, [shareString]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> queueRandomShow() =>
      (super.noSuchMethod(
            Invocation.method(#queueRandomShow, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void showNotification(String? message) => super.noSuchMethod(
    Invocation.method(#showNotification, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void requestPlaybackFocus() => super.noSuchMethod(
    Invocation.method(#requestPlaybackFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> stopAndClear() =>
      (super.noSuchMethod(
            Invocation.method(#stopAndClear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> seekToNext() =>
      (super.noSuchMethod(
            Invocation.method(#seekToNext, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> seekToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#seekToPrevious, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> retryCurrentSource() =>
      (super.noSuchMethod(
            Invocation.method(#retryCurrentSource, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void seekToTrack(int? localIndex) => super.noSuchMethod(
    Invocation.method(#seekToTrack, [localIndex]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GaplessPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockGaplessPlayer extends _i1.Mock implements _i2.GaplessPlayer {
  MockGaplessPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get playing =>
      (super.noSuchMethod(Invocation.getter(#playing), returnValue: false)
          as bool);

  @override
  Duration get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeDuration_1(this, Invocation.getter(#position)),
          )
          as Duration);

  @override
  Duration get bufferedPosition =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPosition),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#bufferedPosition),
            ),
          )
          as Duration);

  @override
  List<_i3.IndexedAudioSource> get sequence =>
      (super.noSuchMethod(
            Invocation.getter(#sequence),
            returnValue: <_i3.IndexedAudioSource>[],
          )
          as List<_i3.IndexedAudioSource>);

  @override
  _i3.ProcessingState get processingState =>
      (super.noSuchMethod(
            Invocation.getter(#processingState),
            returnValue: _i3.ProcessingState.idle,
          )
          as _i3.ProcessingState);

  @override
  _i3.PlayerState get playerState =>
      (super.noSuchMethod(
            Invocation.getter(#playerState),
            returnValue: _FakePlayerState_2(
              this,
              Invocation.getter(#playerState),
            ),
          )
          as _i3.PlayerState);

  @override
  String get engineName =>
      (super.noSuchMethod(
            Invocation.getter(#engineName),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#engineName),
            ),
          )
          as String);

  @override
  String get selectionReason =>
      (super.noSuchMethod(
            Invocation.getter(#selectionReason),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#selectionReason),
            ),
          )
          as String);

  @override
  _i2.AudioEngineMode get activeMode =>
      (super.noSuchMethod(
            Invocation.getter(#activeMode),
            returnValue: _i2.AudioEngineMode.auto,
          )
          as _i2.AudioEngineMode);

  @override
  _i5.Stream<_i3.PlayerState> get playerStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateStream),
            returnValue: _i5.Stream<_i3.PlayerState>.empty(),
          )
          as _i5.Stream<_i3.PlayerState>);

  @override
  _i5.Stream<_i3.PlaybackEvent> get playbackEventStream =>
      (super.noSuchMethod(
            Invocation.getter(#playbackEventStream),
            returnValue: _i5.Stream<_i3.PlaybackEvent>.empty(),
          )
          as _i5.Stream<_i3.PlaybackEvent>);

  @override
  _i5.Stream<bool> get playingStream =>
      (super.noSuchMethod(
            Invocation.getter(#playingStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<_i3.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#processingStateStream),
            returnValue: _i5.Stream<_i3.ProcessingState>.empty(),
          )
          as _i5.Stream<_i3.ProcessingState>);

  @override
  _i5.Stream<Duration> get bufferedPositionStream =>
      (super.noSuchMethod(
            Invocation.getter(#bufferedPositionStream),
            returnValue: _i5.Stream<Duration>.empty(),
          )
          as _i5.Stream<Duration>);

  @override
  _i5.Stream<Duration> get positionStream =>
      (super.noSuchMethod(
            Invocation.getter(#positionStream),
            returnValue: _i5.Stream<Duration>.empty(),
          )
          as _i5.Stream<Duration>);

  @override
  _i5.Stream<Duration?> get durationStream =>
      (super.noSuchMethod(
            Invocation.getter(#durationStream),
            returnValue: _i5.Stream<Duration?>.empty(),
          )
          as _i5.Stream<Duration?>);

  @override
  _i5.Stream<Duration?> get nextTrackBufferedStream =>
      (super.noSuchMethod(
            Invocation.getter(#nextTrackBufferedStream),
            returnValue: _i5.Stream<Duration?>.empty(),
          )
          as _i5.Stream<Duration?>);

  @override
  _i5.Stream<Duration?> get nextTrackTotalStream =>
      (super.noSuchMethod(
            Invocation.getter(#nextTrackTotalStream),
            returnValue: _i5.Stream<Duration?>.empty(),
          )
          as _i5.Stream<Duration?>);

  @override
  _i5.Stream<bool> get heartbeatActiveStream =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatActiveStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> get heartbeatNeededStream =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeatNeededStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<String> get engineStateStringStream =>
      (super.noSuchMethod(
            Invocation.getter(#engineStateStringStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<String> get engineContextStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#engineContextStateStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Stream<int?> get currentIndexStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentIndexStream),
            returnValue: _i5.Stream<int?>.empty(),
          )
          as _i5.Stream<int?>);

  @override
  _i5.Stream<_i3.SequenceState?> get sequenceStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#sequenceStateStream),
            returnValue: _i5.Stream<_i3.SequenceState?>.empty(),
          )
          as _i5.Stream<_i3.SequenceState?>);

  @override
  void reload() => super.noSuchMethod(
    Invocation.method(#reload, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Duration?> setAudioSources(
    List<_i3.AudioSource>? children, {
    int? initialIndex = 0,
    Duration? initialPosition = Duration.zero,
    bool? preload = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setAudioSources,
              [children],
              {
                #initialIndex: initialIndex,
                #initialPosition: initialPosition,
                #preload: preload,
              },
            ),
            returnValue: _i5.Future<Duration?>.value(),
          )
          as _i5.Future<Duration?>);

  @override
  _i5.Future<void> addAudioSources(List<_i3.AudioSource>? sources) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioSources, [sources]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> play() =>
      (super.noSuchMethod(
            Invocation.method(#play, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setHybridHandoffMode(String? mode) => super.noSuchMethod(
    Invocation.method(#setHybridHandoffMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setHybridBackgroundMode(String? mode) => super.noSuchMethod(
    Invocation.method(#setHybridBackgroundMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setHybridAllowHiddenWebAudio(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setHybridAllowHiddenWebAudio, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setHandoffCrossfadeMs(int? ms) => super.noSuchMethod(
    Invocation.method(#setHandoffCrossfadeMs, [ms]),
    returnValueForMissingStub: null,
  );

  @override
  void setHybridForceHtml5Start(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setHybridForceHtml5Start, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setTrackTransitionMode(String? mode) => super.noSuchMethod(
    Invocation.method(#setTrackTransitionMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> seek(Duration? position, {int? index}) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position], {#index: index}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setPrefetchSeconds(int? seconds) => super.noSuchMethod(
    Invocation.method(#setPrefetchSeconds, [seconds]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> seekToNext() =>
      (super.noSuchMethod(
            Invocation.method(#seekToNext, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> seekToPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#seekToPrevious, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setWebPrefetchSeconds(int? seconds) => super.noSuchMethod(
    Invocation.method(#setWebPrefetchSeconds, [seconds]),
    returnValueForMissingStub: null,
  );
}
